### ISSUE TITLE
Tags with / in name considered invalid in GUI.

### ISSUE THREAD

**Issue by hardkrash** [gitx/gitx#100]
When I make releases I place the release in a "folder" e.g.
`releases/1.0.0`
`releases/1.1.1`
`releases/1.2.1`

This is not supported with create tag GUI, so I must make in alternative GUI's or on the command line. A red label with 'Invalid name' appears in the lower right corner.

**Comment by tiennou** [comment]
💯 🌟  !

**Comment by rjmunro** [comment]
@tiennou Is this fixed, or invalid or what? I don't understand your emoji.

**Comment by tiennou** [comment]
Yes, it's fixed. Those emojis were an expression of joy caused by the 100th issue being filed and subsequently fixed 😉 .
