### ISSUE TITLE
Provide prebuilt versions?

### ISSUE THREAD

**Issue by bcomnes** [gitx/gitx#101]
Are there already built builds available somewhere? Would love to see some of the developments being made here.

**Comment by a-hurst** [comment]
Would a build-bot be needed for something like this? Or should the plan long-term be to start up a version system again with point releases (e.g. 0.9.0, 0.9.1) and just manually compile and post the major versions to the "Releases" page on GitHub? If the former, I'm sure given the community interest that some people could figure a system out. I know GitLab CI has macOS buildbot support. If the latter, I think that's worthy of a community discussion too.

**Comment by ksuther** [comment]
Travis supports publishing built copies, which could then be uploaded to S3 or somewhere else (https://docs.travis-ci.com/user/uploading-artifacts/). This would would to be configured by the project owner though.

**Comment by jakirkham** [comment]
Actually [Travis CI can upload GitHub releases]( https://docs.travis-ci.com/user/deployment/releases/ ). Also as [Travis CI supports macOS]( https://docs.travis-ci.com/user/reference/osx/), this is probably the easiest way to go. Just have to build on the oldest supported platform is all.

**Comment by Nerian** [comment]
Some Brew support would be nice too:

Here is how some people did it:
https://github.com/caskroom/homebrew-cask/blob/master/Casks/gitx.rb
https://github.com/caskroom/homebrew-cask/blob/master/Casks/laullon-gitx.rb
https://github.com/caskroom/homebrew-cask/blob/master/Casks/rowanj-gitx.rb

**Comment by tiennou** [comment]
Closing this in favor of #38.
