### ISSUE TITLE
Commit hook failed sheet always commits when dismissing sheet

### ISSUE THREAD

**Issue by ksuther** [gitx/gitx#119]
The problem seems to be that NSModalResponseOK is sent regardless of which button is clicked.

This results in `[PBGitWindowController showCommitHookFailedSheet:infoText:commitController:]` always performing a force commit.

**Comment by tiennou** [comment]
Fixed. It's actually somewhat confusing to have a sheet with a default, OK button that doesn't actually do something. I've also brought the hook output back.
