### ISSUE TITLE
Rebasing onto a commit does not work

### ISSUE THREAD

**Issue by Timmmm** [gitx/gitx#134]
If you have a branch and you right click another commit (*not* a ref), and click "Rebase <your other branch> onto <this commit>" you get an error message that says something like "The operation could not be completed. No further information is available".

I eventually worked out you have to rebase onto a ref.

(This was with HEAD from a few days ago btw.)

**Comment by tiennou** [comment]
Fixed by 760d7c6a141d396aff2cf27964796050b9ed2a01. Thanks for the report !
