### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by digitaljhelms** [gitx/gitx#138]
Fresh clone, unable to build.

---

#### Steps to reproduce

```
git clone --recursive https://github.com/gitx/gitx.git
cd gitx
cd External/objective-git
script/bootstrap
script/update_libgit2
cd ../..
Scripts/build.py build release
```

---

#### Expected behavior

Successful build.

---

#### Observed behavior

```
mvers: ${CURRENT_PROJECT_VERSION}
vers:  0.12
Setting CFBundleShortVersionString of project GitX to:
    0.15.2428 dev.

Updating CFBundleShortVersionString in Info.plist(s)...

Updated CFBundleShortVersionString in "GitX.xcodeproj/../Resources/Info-gitx.plist" to 0.15.2428 dev
Updated CFBundleShortVersionString in "GitX.xcodeproj/../Resources/Info.plist" to 0.15.2428 dev
Setting version of project GitX to:
    0.15.2428.

Also setting CFBundleVersion key (assuming it exists)

Updating CFBundleVersion in Info.plist(s)...

Updated CFBundleVersion in "GitX.xcodeproj/../Resources/Info-gitx.plist" to 0.15.2428
Updated CFBundleVersion in "GitX.xcodeproj/../Resources/Info.plist" to 0.15.2428


** BUILD FAILED **


The following build commands failed:
	Ditto /sandbox/gitx/build/Release/Autoupdate.app/Contents/Frameworks/libclang_rt.asan_osx_dynamic.dylib /usr/lib/clang/9.0.0/lib/darwin/libclang_rt.asan_osx_dynamic.dylib
(1 failure)
error: Command '['xcrun', 'xcodebuild', '-workspace', 'GitX.xcworkspace', '-scheme', 'GitX', '-configuration', 'Release', 'build', 'BUILD_DIR=/sandbox/gitx/build']' returned non-zero exit status 65
```

---

#### Software version(s)

* macOS High Sierra 10.13.3 (17D102)
* Xcode Version 9.2 (9C40b)
* Python 2.7.10

---

#### Additional notes

I am able to successfully build and export an Archive from Xcode directly.

**Comment by stepheneb** [comment]
Seems to be a different issue but you might check out #139

**Comment by tiennou** [comment]
You should not be running `build.py build release`, that actually builds DMGs and Appcasts (sorry, the instructions are not so clear about that). Right now the preferred way is to just use Xcode directly, with the configuration you want.

The specific error stems from the fact that ASan is enabled by default, which seems to confuse some things, and since it's the first time I see it, I'll keep this open as I reminder ASan should be disabled on releases.

**Comment by tiennou** [comment]
This should be fixed in master now, @digitaljhelms I'm closing this but if it still fails feel free to reopen !
