### ISSUE TITLE
Can't build project

### ISSUE THREAD

**Issue by dragos** [gitx/gitx#145]
Not sure if there's any other channel to ask this question.. but here it goes. I can't build the project, and the error message is most likely missing. I followed all the steps on the wiki page up to this call that failed:

```
$ Scripts/build.py build debug
** BUILD FAILED **


The following build commands failed:
	CompileC /Users/dragos/Library/Developer/Xcode/DerivedData/GitX-alksxmwmxqqbvwdijiszikdnzmkq/Build/Intermediates.noindex/ObjectiveGitFramework.build/Debug/ObjectiveGit-Mac.build/Objects-normal/x86_64/GTBlob.o ObjectiveGit/GTBlob.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
error: Command '['xcrun', 'xcodebuild', '-workspace', 'GitX.xcworkspace', '-scheme', 'GitX', '-configuration', 'Debug', 'build', 'BUILD_DIR=/Users/dragos/workspace/oss/gitx/build']' returned non-zero exit status 65
```

If I try to open the project in XCode, I see a bit more:

```
/Users/dragos/workspace/XCodeProjects/gitx/Resources/GitX_Prefix.pch:5:13: fatal error: 'ObjectiveGit/ObjectiveGit.h' file not found
    #import <ObjectiveGit/ObjectiveGit.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang failed with exit code 1
```

I'm sure I'm doing something wrong, but I can't figure out what.

**Comment by mangerlahn** [comment]
Looks like ObjectiveGit is not yet on your system. It is a submodule of Gitx. 
If you have done the steps in the wiki, you should be fine though.
Have you encountered any errors on the way? Did the submodule initialize correctly?

**Comment by dragos** [comment]
No errors as far as I can tell.

```
dragos@aquarius gitx (master) $ git submodule update --init --recursive
dragos@aquarius gitx (master) $ cd External/objective-git
dragos@aquarius objective-git ((17112f53...)) $ script/bootstrap
*** Updating submodules...
*** Checking dependencies...
*** cmake is available
*** libssh2 is available
*** libtool is available
*** autoconf is available
*** automake is available
*** pkg-config is available
dragos@aquarius objective-git ((17112f53...)) $ script/update_libgit2
No update needed.
```

**Comment by dragos** [comment]
Do I need to compile/install objective-git explicitly, or the build script does it for me?

**Comment by tiennou** [comment]
You should be all set. IIRC the prerequisites are that submodules are there and the bootstrap script has been run.

Does it make a difference if you build from Xcode normally ? IIRC you can trigger a build of Objective-Git from the GitX workspace, does that make a difference ?

**Comment by dragos** [comment]
I couldn't find a way to build it from the Gitx workspace, but I opened the Objective-git workspace. Build fails with `/Users/dragos/workspace/oss/gitx/External/objective-git/Carthage/Checkouts/Nimble/Sources/Nimble/Matchers/AllPass.swift:69:33: Cannot use mutating member on immutable value: 'generator' is a 'let' constant`

**Comment by dragos** [comment]
I finally modified the build script to not swallow output, and I found the error:

```
/Users/dragos/workspace/oss/gitx/External/objective-git/ObjectiveGit/GTBlob.m:43:123: error: format specifies type 'ssize_t' (aka 'long')
      but the argument has type 'git_off_t' (aka 'long long') [-Werror,-Wformat]
  ...[NSString stringWithFormat:@"<%@: %p> size: %zi, content: %@, data = %@", NSStringFromClass([self class]), self, [self size], [se...
                                                 ~~~                                                                  ^~~~~~~~~~~
                                                 %lli
1 error generated.
```

I could finally build it by modifying the offending line in the objective-git checkout. Not sure what the proper fix would be, and why I am the only one hitting this error...

My fix is simply to replace `%zi` with `%lli`.

**Comment by dragos** [comment]
This is a duplicate of #139 so I'm closing now.

**Comment by claytonrcarter** [comment]
@dragos do you happen to recall how you "modified the build script to not swallow output"? I'm getting the exact same build error (`'ObjectiveGit/ObjectiveGit.h' file not found`) on current master 9a99f1d0
