### ISSUE TITLE
Command-line usage (rev-list) not working

### ISSUE THREAD

**Issue by dragos** [gitx/gitx#146]
One of the most powerful and useful features IMO is the ability to "slice and dice" commits. In particular, using Gitx instead of `git log` for visual inspection. This used to work a long, long time ago, in another fork (probably the original), but no longer.

According to the docs:

> GitX itself is fairly simple. Most of its power is in the gitx binary, which you should install through the menu. the gitx binary supports most of git rev-list's arguments. For example, you can run gitx --all to display all branches in the repository, orgitx -- Documentation to only show commits relating to the 'Documentation' subdirectory. With gitx -Shaha, gitx will only show commits that contain the word 'haha'. Similarly, with gitx v0.2.1.., you will get a list of all commits since version 0.2.1.

However, `gitx v0.2.1..` shows all commits in the repository, nothing is filtered. Similarly for almost everything else, except for `-s` which pre-fills the search box.

**Comment by tiennou** [comment]
Should be fixed now. The revspec handling wasn't rewired after the switch to libgit2's revwalk. Thanks for the report !

**Comment by tiennou** [comment]
Wait, paths are still no good, so 🤷‍♂️ .

**Comment by tiennou** [comment]
Fixed!

**Comment by dragos** [comment]
Works like a charm! Thank you!
