### ISSUE TITLE
Git output isn't shown on failure

### ISSUE THREAD

**Issue by Timmmm** [gitx/gitx#149]
For example, if I do a `git pull` and it fails because my local changes would be overwritten, I just get an error message saying essentially "git pull failed". It doesn't print the output.

This seems a shame because it looks like the command output is stored in `error.userInfo[PBTaskTerminationOutputKey]` which is propagated all the way to `showErrorSheet`, but then discarded.

I know you are planning to move to `libgit2`, which is a fantastic idea, but until that is done I think `showErrorSheet` should check for the presence of `PBTaskTerminationOutputKey` and show it if found.

I'm using `master` from several weeks ago btw. Apologies if this has already been fixed since then.

**Comment by tiennou** [comment]
Fixed too, thanks for the report !
