### ISSUE TITLE
Push submenu doesn't work

### ISSUE THREAD

**Issue by Timmmm** [gitx/gitx#150]
If you right click a branch and select "Push to"->"origin" (or any other remote) it silently does nothing.

It gets to line 167 in `PGRefMenuItem.m`, where it adds the "origin" submenu with `.representedObject` set to an `NSString` with the value `origin`

			for (NSString *remote in remoteNames) {
				NSMenuItem *remoteItem = [NSMenuItem pb_itemWithTitle:remote action:@selector(pushToRemote:) enabled:YES];
				remoteItem.representedObject = remote;
				[remotesMenu addItem:remoteItem];
			}

When it is clicked we get to `pushToRemote()` in `PBGitWindowController.m`, which calls:

	id <PBGitRefish> refish = [self refishForSender:sender refishTypes:@[kGitXBranchType]];

Unfortunately the `sender` is the "origin" submenu, not the "Push to" menu. The "Push to" menu item's `representedObject` is the git branch but the "origin" submenu's `representedObject` is just the `origin` string. Since it isn't a `kGitXBranchType` it returns null (or whatever Objective-C uses for null) and then the function silently returns.

**Comment by tiennou** [comment]
Fixed, thanks for the report !
