### ISSUE TITLE
Problem building: Undefined symbol "git_buf_dispose"

### ISSUE THREAD

**Issue by claytonrcarter** [gitx/gitx#155]
I get a linking error when trying to build the latest commit, which changed `git_buf_free` to `git_buf_dispose`. 

```
Undefined symbols for architecture x86_64:
  "_git_buf_dispose", referenced from:
      +[PBRepositoryFinder gitDirForURL:] in PBRepositoryFinder.o
ld: symbol(s) not found for architecture x86_64
```

Manually changing it back to `git_buf_free` fixes the build. I'm on 10.12.6 with xcode 9.1 (I think).

The commit in question seems to be 917eee8

**Comment by tiennou** [comment]
Yeah, sorry about that, I was running against libgit2 master, and fixed the warnings in "advance", but we're not there yet. I reverted 917eee8.
