### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by Uncommon** [gitx/gitx#163]
Attempting to build at a01b22d443f312c99465b9b24de8ef9282543ef0 (current master) with Xcode 10.

I got as far as running the Python build script, and it yields this:

    gitx (master)*$ Scripts/build.py build debug
    ** BUILD FAILED **
    
    
    The following build commands failed:
    	ProcessPCH /Users/i58922/Library/Developer/Xcode/DerivedData/GitX-dukxooajdmfnvnbztscupedwxxlm/Build/Intermediates.noindex/PrecompiledHeaders/SharedPrecompiledHeaders/17796502572244314692/GitX_Prefix.pch.gch /Users/i58922/Developer/Personal/gitx/Resources/GitX_Prefix.pch normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.analyzer
    (1 failure)
    error: Command '['xcrun', 'xcodebuild', '-workspace', 'GitX.xcworkspace', '-scheme', 'GitX', '-configuration', 'Debug', 'build', 'BUILD_DIR=/Users/i58922/Developer/Personal/gitx/build']' returned non-zero exit status 65

When I try to build in Xcode, it fails on the cli tool:

    Undefined symbols for architecture x86_64:
      "_git_buf_free", referenced from:
          +[PBRepositoryFinder gitDirForURL:] in PBRepositoryFinder.o
      "_git_repository_discover", referenced from:
          +[PBRepositoryFinder gitDirForURL:] in PBRepositoryFinder.o
      "_git_repository_free", referenced from:
          +[PBRepositoryFinder workDirForURL:] in PBRepositoryFinder.o
      "_git_repository_open_ext", referenced from:
          +[PBRepositoryFinder workDirForURL:] in PBRepositoryFinder.o
      "_git_repository_workdir", referenced from:
          +[PBRepositoryFinder workDirForURL:] in PBRepositoryFinder.o
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

So apparently it's supposed to be linking with libgit2 but is failing somehow.

**Comment by Uncommon** [comment]
I removed the dependency on the cli tool target, and then the app built and ran successfully.

**Comment by wooly** [comment]
I'm still getting this with `9a99f1d`, any thoughts on how to fix?

**Comment by tiennou** [comment]
Note that 9a99f1d05680166fc88ced7eed7b1672edcd1301 changed the scripts around, so the build script is now `./Scripts/build.py debug|release|clean`.

I have no clue as to why there's a linking failure, especially since the app itself links. Those symbols should be provided by Objective-Git, which is a dependency of the cli tool target. Does it still happen ? What does the Xcode build log look like ?

**Comment by wooly** [comment]
Thanks for the prompt reply @tiennou. I've managed to get past it by just starting from scratch so will open a new issue for where I'm at now.

**Comment by virajkanwade** [comment]
Xcode 11.1 it still fails. Almost a year down. Can somebody provide details of how to fix this?

**Comment by hannesa2** [comment]
I guess it's obsolete now, because we can build x86_64 and arm64.
Please reopen if it's still an issue
