### ISSUE TITLE
XSS during multiselect

### ISSUE THREAD

**Issue by shotgundebugging** [gitx/gitx#174]
I don't know how relevant this is or if it's any real security danger, but I'll just drop it here.
I discovered this while committing my pentesting stash.

Steps to reproduce
1. `touch "<img src=x onerror=prompt(document.cookie)>.png"` inside a git repo
2. open GitX
3. In the `Unstaged Changes` panel select the file created at (1) together with another file so that `Multiple Selection` view is shown. This will trigger the XSS

Interacting with the prompt crashed GitX.

GitX version 0.16.2327 dev (0.16.2327) running macOS Mojave 10.14.2 (18C54)

**Comment by nanotech** [comment]
This was fixed in #124, which is newer than the [2327 test release](https://github.com/gitx/gitx/releases/tag/build%2F0.16%2F2327). If you can, build GitX from master to get the fix for now.

**Comment by tiennou** [comment]
I'm closing this, since it seems to be fixed.
