### ISSUE TITLE
Where to find a recent build?

### ISSUE THREAD

**Issue by Pictor13** [gitx/gitx#186]
Has anybody a build for macOS Mojave, to upload and share with us fellow developers?

My machine doesn't have enough space on the hard drive to install XCode and its >6 GBytes.

It would be great if somebody could put a release somewhere. Everybody could benefit from the latest great improvements to GitX.

I have a 1 year old build, but it has some memory leak issue and after 30 minutes it eats more than 1.5GB having just a single repository open 🙁

**Comment by Drarok** [comment]
I uploaded one in [my comment here](https://github.com/gitx/gitx/pull/179#issuecomment-461005727), if you trust a random binary. 

It’s the build I’m using, I think. I could produce a new one, but ideally we’d have nightly builds from a CI service so they can be trusted.

**Comment by Pictor13** [comment]
That's great, you spared me some big hassle, thank you @Drarok!
I trust my SO & antivirus to prevent random binaries from making a mess 😉
It also looks like the memory consumption is more stable now and doesn't leak (for the moment).

I close the issue; hoping to see soon builds compiled automatically via CI 🤓
