### ISSUE TITLE
Push fails but succeeds from command line

### ISSUE THREAD

**Issue by silverki** [gitx/gitx#187]
Versions:

- GitX - Version 0.12 (0.12) built from commit 84555e0d
- MacOS - 10.14.4
- Git -  2.20.1 (Apple Git-117)

Push always fails with error message:

```
An error occurred while pushing master to "origin".

The underlying task failed:

Task exited unsuccessfully

The task "/usr/bin/git --git-dir=[REDACTED] push origin master" returned a non-zero return code

Return code: 128

Output:
ssh: connect to host [REDACTED] port 22: Host is down
fatal: Could not read from remote repository.
```

Same "task" succeeds from command line:

```
$ /usr/bin/git --git-dir=[REDACTED] push origin master
Enumerating objects: 57, done.
Counting objects: 100% (57/57), done.
Delta compression using up to 8 threads
Compressing objects: 100% (48/48), done.
Writing objects: 100% (48/48), 7.82 KiB | 2.61 MiB/s, done.
Total 48 (delta 41), reused 0 (delta 0)
....
$ echo $?
0
```

Initially I suspected connectivity issues, but it always fails from gitX and succeeds from command line.

**Comment by Drarok** [comment]
Do you have an application-level firewall installed, or is the hostname of the remote weird in any way? Perhaps an alias in `~/.ssh/config`?

**Comment by silverki** [comment]
@Drarok Thank you for the hint. Connection was blocked by firewall. Perhaps it helps others. Little Snitch seems to block all traffic when application is changed. I had rules in place, but those were overridden by block rule when I built new version.
