### ISSUE TITLE
Reproducible builds and app sandbox

### ISSUE THREAD

**Issue by pshirshov** [gitx/gitx#194]
I was able to build GitX with app sandbox and hardened runtime on. 

It even passes notarization and app store verification

Though:

1. It was hard - I had to mangle with multiple configuration issues and get rid of dymamic linking with openssl
2. Seems like it's not possible to run git process under sandbox.

I think it's a good idea to think about porting app to modern APIs. Also it may be a very good idea to employ a package manager (like Carthage) and make the builds reproducible. At this point it's insanely hard to get a redistributable working build.

**Comment by pshirshov** [comment]
[GitX.app.zip](https://github.com/gitx/gitx/files/3750766/GitX.app.zip)

A fully working and notarized app build without sandbox

**Comment by plan44** [comment]
Thanks a lot for your work! At least it makes this snapshot accessible for those who otherwise stuble somewhere in the build process (like I did)! Of course I agree with you that any steps towards automating a redistributable build would be great.

**Comment by johansolve** [comment]
> [GitX.app.zip](https://github.com/gitx/gitx/files/3750766/GitX.app.zip)
> 
> A fully working and notarized app build without sandbox

Thanks! But crashes for me when opening repo. 
`OS Version:            Mac OS X 10.13.6 (17G8030)
Termination Reason:    DYLD, [0x4] Symbol missing

Dyld Error Message:
  Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/GitX dev build/GitX.app/Contents/MacOS/../Frameworks/ObjectiveGit.framework/ObjectiveGit
  Expected in: /usr/lib/libSystem.B.dylib

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   dyld                          	0x000000010bdc424a __abort_with_payload + 10
1   dyld                          	0x000000010bdc3bbc abort_with_payload_wrapper_internal + 89
2   dyld                          	0x000000010bdc3be9 abort_with_payload + 9
3   dyld                          	0x000000010bd97482 dyld::halt(char const*) + 354
4   dyld                          	0x000000010bd975a9 dyld::fastBindLazySymbol(ImageLoader**, unsigned long) + 170
5   libdyld.dylib                 	0x00007fff5e21a292 dyld_stub_binder + 282
6   org.libgit2.ObjectiveGit      	0x0000000107cf9000 0x107b63000 + 1662976
7   org.libgit2.ObjectiveGit      	0x0000000107c26f12 find_repo + 194
8   org.libgit2.ObjectiveGit      	0x0000000107c27b90 git_repository_discover + 176
9   io.7mind.oss.gitx             	0x0000000107a89b3b 0x107a33000 + 355131
10  io.7mind.oss.gitx             	0x0000000107a6881a 0x107a33000 + 219162
11  io.7mind.oss.gitx             	0x0000000107a78f3e 0x107a33000 + 286526
12  com.apple.AppKit              	0x00007fff33a8a86d -[NSDocument _initWithContentsOfURL:ofType:error:] + 172
13  com.apple.AppKit              	0x00007fff33a8a752 -[NSDocument initWithContentsOfURL:ofType:error:] + 231
14  com.apple.AppKit              	0x00007fff33b602a5 -[NSDocumentController makeDocumentWithContentsOfURL:ofType:error:] + 628
`

**Comment by pshirshov** [comment]
That's strange... It works for me. Could you try to give it full disk access?..

**Comment by johansolve** [comment]
It's on High Sierra 10.13 so no limitation on disk access

**Comment by plan44** [comment]
YFYI: Works perfectly for me on Mojave 10.14.6 (18G103), for all my repos.
Had no need to give it full disk access.

**Comment by pshirshov** [comment]
Ah, High Sierra. Sorry, I have no capacity to check what's wrong with it.

**Comment by pshirshov** [comment]
See https://github.com/gitx/gitx/pull/195
Should be lot easier to build now
Though I didn't manage what to do with autoupdater app - have no idea how to sign it.

**Comment by pshirshov** [comment]
[GitX.app.zip](https://github.com/gitx/gitx/files/3753203/GitX.app.zip)

Another build, with working command line launcher and bigger fonts.

**Comment by vng** [comment]
@pshirshov Where did you change font sizes? Can you make a commit for that?

**Comment by rjmunro** [comment]
@pshirshov I found the "Another build, with working command line launcher and bigger fonts." build seemed to get into a state where it span up hundreds and hundreds of git processes until my computer ran out of memory. It happened a couple of times. I have "Watch for changes in repositories" enabled, which I guess might be part of it.

**Comment by hannesa2** [comment]
No we are able to build it on CI and I created a new release https://github.com/gitx/gitx/releases/tag/0.17
But we have issues to build it locally  https://github.com/gitx/gitx/issues/239 please continue there
