### ISSUE TITLE
Switch submodules to subtrees

### ISSUE THREAD

**Issue by jasonkarns** [gitx/gitx#197]
The repository currently relies on submodules to pull in dependencies. This adds additional complexity to the build process which (until this is built by homebrew) is necessary for virtually everyone.

git-subtree is a mechanism to pull in dependencies in such a way that a standard clone is all that's necessary to get a complete working copy of the repository. It would not require any submodule management or recursive clones/updates.

I'd be happy to open a PR converting from submodules to subtrees if the current maintainers would accept such a change.

**Comment by jspiro** [comment]
Yes! https://github.com/gitx/gitx/issues/206

**Comment by hannesa2** [comment]
I've a strong opinion against this.

With git-subtree you can't easy verify what's changed in the meanwhile like https://github.com/gitx/MGScopeBar/pull/2#issuecomment-767069775 and contributing code back upstream for the sub-projects is slightly more complicated.

**Comment by jspiro** [comment]
Fair point.

**Comment by jasonkarns** [comment]
> contributing code back upstream for the sub-projects is slightly more complicated.

Is it? `git subtree push --prefix=path/to/dep/ remote-dep-repo ref`

But I do acknowledge that subtree is more useful when the dep is primarily being consumed, not also developed, so this could be a blocker.

> With git-subtree you can't easy verify what's changed in the meanwhile
I might be misunderstanding what you mean, because it's still trivial to get a log or diff of upstream changes. The entire history of the dep is available and is fetched as a remote just like any other remote.
