### ISSUE TITLE
Announcing gitx-community

### ISSUE THREAD

**Issue by jspiro** [gitx/gitx#206]
Welcome to the final fork. Join us at https://github.com/gitx-community/gitx

There's too much promise in this simple but powerful tool. Too many hours of unrequited community development. `gitx/gitx` has not proven itself to be run in the best spirit of open source.

If you want to become a maintainer, [we'd love to have you](https://github.com/gitx-community/gitx/discussions/4)!

**Comment by bradvogel** [comment]
THANK YOU for doing this! GitX is still by far the best git tool, by far. Glad to see the renewed attention.

**Comment by tiennou** [comment]
Hey, I'm not against having new maintainers here, actually, so forking again is really weird… I've been burnt out pretty heavily, so my implication somewhat waned, but I don't mind keeping the organization contained.

**Comment by tiennou** [comment]
@jspiro I've added you as an administrator to this org. We have a Slack channel somewhere as well.

> has not proven itself to be run in the best spirit of open source.

Please. Really ? Let me just say that sometimes, even with the best of spirits, life gets in the way 😩.

**Comment by hannesa2** [comment]
>  I've added you as an administrator to this org

Ahhh, when the current maintainer @tiennou writes this, I see the new https://github.com/gitx-community/gitx is obsolete and you @jspiro can delete this https://github.com/gitx-community/gitx organization to avoid confusion and we can continue in this organization/repo again ! 🥇 👍 

I love to see now two active maintainers. Just a question: is this enough ?

**Comment by jspiro** [comment]
@tiennou Please do not take offense, maybe this is how it had to happen for us both. I fully understand life getting in the way, I've been burned out for the better part of this decade. I was going on observation of stagnation, I hope you can understand how I saw it.

Thank you for making me a maintainer–I think there is room for there to be a few of us, do you agree? Are you also open to me setting up Discussions and Projects–is there anything you are against? This is a collaboration, but if you want to stay back then that's cool too.

Ack, @hannesa2. Let's get your Actions working, a perfect way to kick off some new releases!

**Comment by jspiro** [comment]
@tiennou Are you comfortable making me a maintainer of gitx org? Otherwise can you please add me to the other repos too, so we can update our dependencies and add e.g. Issues tabs?

**Comment by hannesa2** [comment]
@tiennou Please share your power to avoid asking you for something. Thank you !

**Comment by tiennou** [comment]
I've added both of you to the Core team of the gitx org, which I hope is enough to give you access to all repositories (not certain though, it's been a while). There's actually a few people in that team which had a hand in the project at a time or another. I myself can't say I'll be able to participate, but I'll be glad to bounce ideas and reviews, or low-level libgit2/objective-git "work" 😉.

If you want to enable Projects & Discussions, feel free to do so. We had a Slack channel set up for that purpose, which predates GH's Discussion feature, so 🤷‍♂️.

**Comment by hannesa2** [comment]
> Ack, @hannesa2. Let's get your Actions working, a perfect way to kick off some new releases!

@jspiro 
This is a pre-task https://github.com/gitx/MGScopeBar/pull/2 Are you receive notification from that repo too ?

**Comment by jspiro** [comment]
Ack. Closing this.
