### ISSUE TITLE
Strange Preferences window

### ISSUE THREAD

**Issue by vng** [gitx/gitx#219]
- Here is how Preferences window looks like:
<img width="481" alt="Screen Shot 2021-02-03 at 09 47 00" src="https://user-images.githubusercontent.com/175612/106709015-e7cff500-6604-11eb-859f-4a4f7a944f98.png">

- Can we add Font size settings?

**Comment by vng** [comment]
This is how it was before:
<img width="402" alt="Screenshot 2022-02-15 at 15 05 09" src="https://user-images.githubusercontent.com/175612/154059113-c63a36f6-5dc1-4294-94cb-a9b7ec284bef.png">

**Comment by ADTC** [comment]
@vng I have opened a PR for improving the settings window. The screenshots are in the PR.

> Can we add Font size settings?

Could you please make this a separate issue and add more details on exactly what you're expecting?
