### ISSUE TITLE
Prebuilt?

### ISSUE THREAD

**Issue by kwerle** [gitx/gitx#221]
Is the most recent prebuilt version really from 2018?

**Comment by hannesa2** [comment]
Yes, and you are warmly welcome to contribute to have a recent version

**Comment by rjmunro** [comment]
I'm using the build attached to this ticket: https://github.com/gitx/gitx/issues/194

**Comment by claytonrcarter** [comment]
FYI you can now download prebuilt binaries from CI. It ain't pretty, but it'll work in a pinch. (x86 only ATM, sorry)

Go to https://github.com/gitx/gitx/actions?query=branch%3Amaster and click on the first workflow run, at the top of the list, to open the summary of that run. Now look for the section (near bottom of page) for the "Artifacts" and select which ever one you want. It will download a zip which extracts a dmg which contains the app. 🙄 You'll have to option+click and select "Open" to force it to open.

**Comment by hannesa2** [comment]
No we are able to build [automatic releases](https://github.com/gitx/gitx/pull/258) as well https://github.com/gitx/gitx/releases/tag/0.17
