### ISSUE TITLE
Should this not be a fork?

### ISSUE THREAD

**Issue by jakirkham** [gitx/gitx#23]
Some GitHub features like searching don't work great with forks. Would it be worthwhile to just make this a proper repo instead of a fork?

**Comment by tiennou** [comment]
I'd be interested in having a list of issues instead of hand-waving 😉 . We actually decided to keep the "heritage" apparent, and I was thinking that having us stick out in the network graph would be a good way to find us.

**Comment by svintus** [comment]
+1 For keeping it a fork, that's exactly how I just found this repo.

**Comment by andreif** [comment]
Even if the network graph is amazingly horrific to use for popular repos, it's still a perverse-but-working way to find active forks. Every time I have to use it, I feel that I must code something to replace that horror NOW 😱

**Comment by tiennou** [comment]
Closing because we're just discussing, right 😉 ? I feel like keeping our ancestry apparent is better anyway. I'd bet once we got starred enough, the searching will "fix" itself.

**Comment by jakirkham** [comment]
Obviously if the core secs are happy with the status quo, that's fine. Just raising the idea.

FYI by searching I meant searching the code (e.g. for function `foo`). GitHub doesn't support this on forks. I realize re-reading the OP that this is unclear. Unless GitHub changes that, there won't be any improvement.

As far as other pros/cons I don't know a list and had looked for one when I posted this, but had no luck finding one. A quick Google doesn't seem to help now either. Maybe ask GitHub if you are still interested in a comparison. Though I'm guessing you are not.
