### ISSUE TITLE
Build Instructions

### ISSUE THREAD

**Issue by janeklb** [gitx/gitx#240]
The [build instructions](https://github.com/gitx/gitx/wiki/Build-instructions) (referenced in the readme) wiki page was last updated in 2019 - are the instructions listed there still the current / preferred / correct way to build gitx?

**Comment by hannesa2** [comment]
Please have a look on CI https://github.com/gitx/gitx/blob/master/.github/workflows/BuildPR.yml
It builds without Phython

**Comment by janeklb** [comment]
Thanks @hannesa2 
Quick followup: Do gitx's GH actions builds produce any (downloadable) binary / artefacts?

**Comment by hannesa2** [comment]
It would be a nice goal, but currently not, but there is a blueprint how to archive this https://github.com/utmapp/UTM 

... someone has do apply it.
