### ISSUE TITLE
Stage menu

### ISSUE THREAD

**Issue by tiennou** [gitx/gitx#25]
Since #24 took me by surprise, I'd like to propose adding a new top level menu between Repository and View, that would correspond to actions available in (surprise) the Stage view.

Right now, that means moving the "Stash Save/Pop" menu items, adding a real checkboxy "Amend" item with that #24 shortcut, and <kbd>⌘↩</kbd> for "Commit" (and "Sign-off", because I now suspect it has one).

**Comment by elia** [comment]
@tiennou would be great!

That would also make possible to use the search field in the help menu (<kbd>⇧⌘?</kbd>) to reach actions with the keyboard even in absence of key equivalents.

**Comment by ssp** [comment]
@tiennou Sounds like a good idea to me. If none of you haven done so already, I can try to look into this in the coming days.

Once that is done, with the commonly use menu items available via keyboard equivalents, what would you think about removing the – IMO weird – behaviour of the controls beneath the stage view when holding the option key? At least I find it rather distracting that pressing the option key while typing will cause so much flickering at the bottom of the window.

**Comment by tiennou** [comment]
Haven't. I planned to, but then got carried away trying to fix the view hierarchy. Feel free to tackle that.

As per the flickering, I'm not sure, there's quite a bunch of GUI, and it seemed like an obvious solution. Here's my thought :
- "Amend" must stay, it's modal (you're editing the previous commit).
- The commit message doubles as the stash comment.
- Give super-powers to the commit button, so it gains a menu when <kbd>⌥</kbd> is held, with "Commit", "Stash", "Stash and keep index".
- Maybe make "Sign-off" a checkbox ? I never use(d) it, and now that I know what it does, I feel like a whole button just to add a few lines in the commit message is unwarranted. But I also don't know what the rules are for sign-off, so...

**Comment by nanotech** [comment]
+1 on a stage menu, adding more menu items that correspond to window buttons and checkboxes is great.

I agree that a sign-off checkbox would be a better fit than the current button. Visually it looks like it will add the sign-off line and also trigger a commit, but it just adds the line. Unchecking a checkbox is also simpler than manually deleting the line if you want to remove it.

The hold-⌥-for-staging UI is also rather weird (unusual in relation to OS conventions) to me. Some options: 

- Replace the Sign-Off button with Stage, holding ⌥ toggles the button to Stage and Keep Index. Cons: No discoverability improvement, needs another modifier if we add `--include-untracked`.
- Super-powered commit button with a menu, like the Github merge button. Cons: No built-in Cocoa control for this, AFAIK. Segmented control + NSMenu?
- Commit and Stage tabs below or beside the commit controls. Cons: Uses more space?
- Menu item with a separate modal dialog. Cons: Stashing uses all the same UI as committing, especially if you use `--keep-index`.

**Comment by ssp** [comment]
closing this now that #50 and #55 are in
