### ISSUE TITLE
How should we handle accepting pull requests

### ISSUE THREAD

**Issue by ssp** [gitx/gitx#26]
Hi everybody – and @tiennou and @nanotech in particular,

do we have a common idea how we should handle pull requests? How they should be accepted and who should merge them in which way? With some of the PRs we currently have, it’s not clear to me and I don’t want us to end up stalling unnecessarily just because everybody is waiting for everybody else to press the button.

Say in #19 … things look to me depending on the way my question is answered, so – as far as I am concerned, I’d be happy if @tiennou put the commit in if no further change is necessary. The other way round, I think #16 could be fine now but thought it may be a bad style to merge my own PR in.

I don’t want this to end in loads of process, yet I think a common understanding of our expectations would be good to create a good experience for everybody wanting to contribute.

Also: How should we add PRs to the main branch? Personally I find projects easier to follow using the »Rebase and Merge« option rather than proper merging, but I guess everybody may have their own preferences there.

Just my €0,02

**Comment by nanotech** [comment]
How we've been handling PRs so far has been fine, I think, but it wouldn't hurt to write down a process. If I can summarize, what we've been doing is

- Send PRs for code review by at least one other contributor, and the reviewer merges when satisfied.

I think it's fine to merge your own PRs once they've been reviewed, and either the requester or a reviewer could merge. For larger PRs like #16 that might require multiple revisions, the requester has the best idea of when they're done working on it.

About clarity, also on #16, I left a :+1: reaction on your (@ssp's) last comment to express that I think it's ready to merge, but I should probably instead leave a comment saying "I think this is ready to merge" and be perfectly clear.

For #19, @tiennou has worked on the graphing code before and probably has the best idea of how it works. In cases like that, I think it's fine to go ahead and merge if there are no objections. The codebase:contributors ratio is high enough that there might not always be another contributor with enough time or experience with a particular component that feels confident saying "absolutely ok to merge".

In general, I think most PRs are not changing critical code that could cause data loss, so the risk of merging eagerly is low. Cosmetic bugs can always be fixed or reverted later, and we can prioritize low friction for low risk changes.

On merge commit vs rebase, I also prefer rebase myself, but more important is that we pick one and use it consistently.

**Comment by elia** [comment]
_Disclaimer: I don't mean to propose this as necessarily better for this project, but just to offer an alternative way from which you can pick what's more suitable for your workflow (aka my 2¢)._

> About clarity, also on #16, I left a 👍 reaction on your (@ssp's) last comment to express that I think it's ready to merge, but I should probably instead leave a comment saying "I think this is ready to merge" and be perfectly clear.

I think you can leave "approving" reviews directly and they'll appear with the green check mark. 

> On merge commit vs rebase, I also prefer rebase myself, but more important is that we pick one and use it consistently.

Alternatively:

- **rebase** for single commits
- **squash** for long lists of commit that document the history that brought the solution but have no value in a blame
- **merge** when every commit is meaningful and it's useful to have each one of them appear separately in a blame

**Comment by nanotech** [comment]
> I think you can leave "approving" reviews directly and they'll appear with the green check mark.

Oh, good point. I forgot that that exists now.

> Alternatively:

Yeah, these are good use cases. I think rebasing multiple commits is also okay if they make sense independently and keeping them grouped by the PR they're from is not important. (e.g. implementing prerequisites for the main feature.)

**Comment by tiennou** [comment]
Personally I've taken the amount of 👍  from you guys as a cue that you were fine with some PR.
But 👍  for reviews, since that makes it clearer that someone really eye-balled the code.

My workflow is usually to keep branches clean via frequent rebasing, but perform merges against master (IOW `--no-ff`). That makes incoming code explicit, and IMHO easier to see if a change was part of some PR or not. I think that's what GitHub calls Rebase and Merge.

**Comment by tiennou** [comment]
Closing, as I think we're in agreement 😉 . Feel free to reopen (or discuss on Slack).
