### ISSUE TITLE
Release 0.18 crashes on Apple Silicon when hard-coded library paths are not found

### ISSUE THREAD

**Issue by lifepillar** [gitx/gitx#276]
I have just downloaded release 0.18 (arm variant), but it crashes when I open it. This is the relevant part of a crash report:

```
Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: /opt/homebrew/*/libcrypto.1.1.dylib
Referenced from: /Applications/GitX.app/Contents/Frameworks/ObjectiveGit.framework/Versions/A/ObjectiveGit
Reason: tried: '/opt/homebrew/*/libcrypto.1.1.dylib' (no such file), '/usr/local/lib/libcrypto.1.1.dylib' (no such file), '/usr/lib/libcrypto.1.1.dylib' (no such file)
(terminated at launch; ignore backtrace)
```

If libcrypto is found, a similar crash happens if libopenssl is not found:

```
Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: /opt/homebrew/*/libssl.1.1.dylib
Referenced from: /Applications/GitX.app/Contents/Frameworks/ObjectiveGit.framework/Versions/A/ObjectiveGit
Reason: tried: '/opt/homebrew/*/libssl.1.1.dylib' (no such file), '/usr/local/lib/libssl.1.1.dylib' (no such file), '/usr/lib/libssl.1.1.dylib' (no such file)
(terminated at launch; ignore backtrace)
```

For now, I have fixed the problem by symlinking those libraries (which I have under `/opt/local`) into `/usr/local`, but this is a very fragile solution. GitX should not rely on libraries that do not reside in system paths: those should be bundled within the app.

**Comment by hannesa2** [comment]
This is my local situation

<img width="542" alt="image" src="https://user-images.githubusercontent.com/3314607/153804993-e3babe4a-dd7f-47ad-8b41-7ebada315dc8.png">

<img width="509" alt="image" src="https://user-images.githubusercontent.com/3314607/153805183-60e25fc8-54e7-4cbf-91a4-d7354f80cf26.png">

<img width="436" alt="image" src="https://user-images.githubusercontent.com/3314607/153805300-6791a959-c2a8-4e8e-bf84-bc3f5f24dd4e.png">

I guess this probably help
`brew update && brew upgrade && brew cleanup && brew doctor`

If you know a better solution please share it with a pull request. I'm happy to merge it !

**Comment by lifepillar** [comment]
That assumes that users use Homebrew, and that it is installed in the default location. At a minimum, that should be listed as a requirement in the Readme or in the release notes.

As I said, I think that the proper solution would be to embed those libraries in the app. Time permitting, I may try to build GitX from source in my environment without Homebrew.

Anyway, with the workaround I have mentioned, I am able to run GitX, which makes me super happy because this is the best Git client for macOS IMO. Thank you very much for bringing this app back to life and please keep up with the good work!

**Comment by hannesa2** [comment]
https://github.com/gitx/gitx/pull/234#issuecomment-1038083715

**Comment by justincbeck** [comment]
@lifepillar is right but you guys are friggin' rock stars for getting this going again. I had no issues with the DMG but I had been idly playing with the project trying to get it built also so I have the right libs in the right place.

Thank you, so much. I've been a GitX user for a really long time (hanging on to a super old binary) and was sad when I switched to an M1 and could no longer use it. I tried GitTower (waaaay too expensive) and Fork, but my heart is with GitX.

Seriously, I cannot thank you enough. :heart:

**Comment by kwerle** [comment]
Please remove homebrew dependency.

**Comment by claytonrcarter** [comment]
@kwerle We would love to. If you have any assistance to offer, PRs are always welcome. Thank you.

**Comment by kwerle** [comment]
> @kwerle We would love to. If you have any assistance to offer, PRs are always welcome. Thank you.

It's been more than a couple of decades since I've really used XCode.  And this answer is pretty old, too:

https://stackoverflow.com/questions/458805/force-static-linking-of-library-linked-to-xcode-target

> In reaction to your comment on Eduard Wirch' answer: you can also control static linking for this one library only, if you replace -lhdf5 by -l/full/path/to/libhdf5.a

**Comment by hannesa2** [comment]
Yes, this is how it works when you build for x86 only, but how to do it dependent on architecture ?

My idea is/was to set a variable in pre build phase script like I did here https://github.com/gitx/gitx/pull/257/files#diff-0dcada5e97bd0f64a385604ca60b1f2dcb4f2f8c66d8b361a1c15526398e0130R1477
But where to use this `$(ENV_VARIABLE_NAME)` variable to link either `x86_64` or `arm64` ?
**This is the right question !**

The solution is maybe here https://nshipster.com/xcconfig/ but I've to less knowledge

**Comment by hannesa2** [comment]
@kwerle @lifepillar @claytonrcarter You guys found/complained/reported the non static linked issue

I guess #296 solves it, please can you test the [artifact](https://github.com/gitx/gitx/actions/runs/1941776152) of this pull request on a x86 mac, if it really solves this issue
I don't have such a machine any more. Thank you !

**Comment by lifepillar** [comment]
I have tried the build with Xcode 13.2.1 on an iMac with High Sierra, and it works! I hope an arm variant will be made available as well. Great job, thanks!

**Comment by hannesa2** [comment]
Great, I will merge it and create a new release with arm64 as well. Thank you @lifepillar
