### ISSUE TITLE
Signing is missing

### ISSUE THREAD

**Issue by hannesa2** [gitx/gitx#278]
Can anyone help to sign our artifacts in release ?

**Comment by hannesa2** [comment]
As I understand, we need someone who already join the Apple developer program.
I don't have such a thing, otherwise I would share it already.
For the guy, who hopefully share his one: I will give you admin rights and you can add your secrets by yourself, and nobody will be able to read it. 

Like I did with my token 

![image](https://user-images.githubusercontent.com/3314607/154422165-cf93d0c4-23a5-43b0-b5c3-b24ad6781af9.png)

**Comment by hannesa2** [comment]
But as long, as I build arm64 artifact locally (because there is not M1 runner) this signing will be not available for arm64 artifacts 👎

We need  this custom runner too https://github.com/gitx/gitx/issues/289

**Comment by akx** [comment]
The [alt-tab-macos](https://github.com/lwouis/alt-tab-macos) project by @lwouis (which I've helped with back in the day :) ) has a GHA-powered release + signing flow... Maybe there's some help to be found in @lwouis's direction? :)

**Comment by lwouis** [comment]
Hi @akx. Actually AltTab uses Travis for CI/CD. Travis supports Apple Silicon VMs btw. It's all free for OSS, after you contact them.

Regarding signing with a developer certificate, i'm afraid i don't know this projet and its leaders enough to share my account key. It has my address, bank details, credit card, etc.

**Comment by hannesa2** [comment]
This is the most interesting part https://github.com/lwouis/alt-tab-macos/blob/master/scripts/package_and_notarize_release.sh#L13-L38 for notarization.

@lwouis It's ok to not trust anonymous accounts/guys, even when they can't read secrets. But just as an idea: you could fork this repo and put notarization and release there. Doing nothing is also fine.

**Comment by akx** [comment]
@lwouis Hi and sorry for tagging you in our of the blue like this :)

To be clear I didn't of course expect you to share any credentials right away, just thought you'd have pointers (and you did!).

**Comment by insha** [comment]
@hannesa2 I have an Apple Developer account and I can help sign the artifacts. However, I will need help on what is needed.

**Comment by hannesa2** [comment]
@tiennou please can you add @insha to https://github.com/orgs/gitx/people to enable him to specify the credentials by himself ?
Otherwise he has to send me the credentials

**Comment by hannesa2** [comment]
I made a WIP pull request https://github.com/gitx/gitx/pull/332
@insha I invited you as admin, please can you update these secrets with the right values
![image](https://user-images.githubusercontent.com/3314607/189595980-61839b2b-4303-4887-99a3-bb56eb921756.png)

Then I can continue with #332

**Comment by insha** [comment]
> I made a WIP pull request #332 @insha I invited you as admin, please can you update these secrets with the right values ... Then I can continue with #332

@hannesa2 Done.

**Comment by hannesa2** [comment]
Any idea ?
<img width="993" alt="image" src="https://user-images.githubusercontent.com/3314607/189754141-ea740988-a9bf-4265-8e73-0643b426f5bd.png">

**Comment by insha** [comment]
> Any idea ? <img alt="image" width="993" src="https://user-images.githubusercontent.com/3314607/189754141-ea740988-a9bf-4265-8e73-0643b426f5bd.png">
> 
> Maybe you can try this command locally ?

update the password to be an app-specific password; give it whirl and let me know :)

**Comment by hannesa2** [comment]
Here is the output of last invalid run https://github.com/gitx/gitx/pull/332#issuecomment-1244895443 
Let us move the conversation to pull request.

**Comment by hannesa2** [comment]
Solved by #335
