### ISSUE TITLE
Release notes on releases

### ISSUE THREAD

**Issue by claytonrcarter** [gitx/gitx#287]
The release notes for our automated releases appear to be a bit too generous w/ what's included in the changelog. The changelong action appears to think that `v0.8.4` was the last tag: https://github.com/gitx/gitx/runs/5226294757?check_suite_focus=true#step:4:17. I assume that this has something to so w/ sorting and comparing the different tag formats we have. 

2 options come to mind: 
1. get the latest tag in CI and pass it to changelog job as `fromTag` configuration. Something like this this might work: `git tag | grep -v ^v | grep -v ^build | sort -V | tail -1`
2. in the `.github/changelog-configuration.json` file, specify a `tag_resolver.filter` value w/ a regex to filter the tags it searches. Something as simple as `^\d` would work, since all the older tags started w/ a letter (either `v` or `build`). More info here: https://github.com/mikepenz/release-changelog-builder-action#configuration-specification

\# 2 sounds easiest and avoids having to capture, define and pass variables around in CI

**Comment by hannesa2** [comment]
Yes, 2 sounds easiest, please see #288

**Comment by hannesa2** [comment]
Why [here](https://github.com/gitx/gitx/runs/5226294757?check_suite_focus=true#step:4:17) exactly the `v0.8.4` was used... no clue
![image](https://user-images.githubusercontent.com/3314607/157176962-2e073e8f-818c-4f2c-b5d6-cc6964dc6666.png)

**Comment by hannesa2** [comment]
I guess it's solved with #320 
If you don't think so, please reopen it again.
