### ISSUE TITLE
Open submodule in GitX on context ("right-click") menu

### ISSUE THREAD

**Issue by claybridges** [gitx/gitx#29]
For instance, in the commit view, right-clicking on a dirty submodule might look like this:

![screen shot 2017-02-06 at 12 48 54](https://cloud.githubusercontent.com/assets/96004/22659207/c979622a-ec6a-11e6-85cd-f54da6d9e379.png)

The `Open "submodule-name"` item just opens that folder in Finder (and so is redundant). It would be nice to have a "Open submodule in GitX..." line.

**Comment by ssp** [comment]
@claybridges Sounds like a nice idea … I’ll try to work it into the reworking of the Stage Menu items I am currently busy with.

**Comment by ssp** [comment]
This should be solved now that #55 has been merged.
