### ISSUE TITLE
GH pages site is broken

### ISSUE THREAD

**Issue by hannesa2** [gitx/gitx#292]
Or GH pages site is broken https://gitx.github.io/gitx/ delivers a **404**

<img width="350" alt="image" src="https://user-images.githubusercontent.com/3314607/154635541-8cc8a364-146b-40b3-8fc5-edf4a65ad51d.png">

<img width="514" alt="image" src="https://user-images.githubusercontent.com/3314607/154634414-d44cb191-14f3-4c36-b242-65944ac54ae4.png">

But this is still working http://gitx.github.io/
![image](https://user-images.githubusercontent.com/3314607/154634691-8b657f51-c7a1-4208-a4e7-44c773656c80.png)

**Comment by hannesa2** [comment]
## A: Previous we used this settings:
<img width="401" alt="image" src="https://user-images.githubusercontent.com/3314607/154635620-de496cae-b9f9-4676-b8de-9114e556b93c.png">

And this is how the files state 
<img width="585" alt="image" src="https://user-images.githubusercontent.com/3314607/154635750-673ccd01-9da0-4e1d-b961-218d817e9914.png">

## B: No we have this:
<img width="717" alt="image" src="https://user-images.githubusercontent.com/3314607/154636023-313cec56-c107-4210-9ede-aa65611f45aa.png">

A single file is for GH pages too less.
<img width="516" alt="image" src="https://user-images.githubusercontent.com/3314607/154636390-98f764f6-0071-4792-a70f-bdae93d9fbe6.png">

## C: Even branch gh-pages would not work

This ab273308eb deleted the content

<img width="403" alt="image" src="https://user-images.githubusercontent.com/3314607/154636345-f5d49e86-db76-4511-8ff4-4f30c709ef40.png">

**Comment by hannesa2** [comment]
This issue is just to keep attention to pages content an well, not only on `appcast.xml`

**Comment by tiennou** [comment]
I think it's normal? Deploying from `gh-pages` (as you needed to do to get the releases from the main repo for the appcast.xml instead of the web one) will always deploy to a `/$repo/` suffix, https://gitx.github.io/gitx/ in that case. It just means that the web repo handles https://gitx.github.io, and `/gitx` is Sparkle's special place.
