### ISSUE TITLE
Update check dialog is incorrect

### ISSUE THREAD

**Issue by rherban** [gitx/gitx#298]
Using the built-in Check for Updates tells me a new update is available, but also says I'm up to date.

![image](https://user-images.githubusercontent.com/14228280/157059458-95a6d2ef-dc1b-4318-9a3b-d3f90de62a22.png)

**Comment by claytonrcarter** [comment]
Yes, sorry about this. The 0.17 and 0.18 versions had incorrect settings which tricked Sparkle into thinking it was all up to date, hence this dialog. Versions 0.18.1+ should show the correct info when an update is available. After you update, if you continue to see this, please reopen this and I'll try to look into it further.
