### ISSUE TITLE
Build failed because in macOS 12.3 python2.7 has been removed

### ISSUE THREAD

**Issue by longbow007** [gitx/gitx#302]
In latest macOS 12.3 Apple has removed python2.7, so the build.py failed
`Scripts/build.py release`
`env: python: No such file or directory`
I used 
`python3 Scripts/build.py`
and succeeded. 
You need to modify the build.py to support python3

**Comment by hannesa2** [comment]
`scripts/build.py` is no more supported to build project. Please see https://github.com/gitx/gitx/blob/master/.github/workflows/BuildPR.yml#L27-L30

Of course you can bring it back to live with a pull request, if you want
