### ISSUE TITLE
Double-clicking branch labels to checkout stopped working

### ISSUE THREAD

**Issue by tiennou** [gitx/gitx#303]
It seems the ability to checkout a branch by double-clicking its label is gone. That was a helpful shortcut for moving around. Is that a side effect of updating or something you took away? Just wondering…

**Comment by claytonrcarter** [comment]
Hmm, I also noticed this recently, but I hadn't used it enough to know if it had worked before or I was just imagining it. 😄 It's not intentional, as far as I know.

**Comment by tiennou** [comment]
Fixed by #328.
