### ISSUE TITLE
How to enable GPG-signing of commits?

### ISSUE THREAD

**Issue by andreif** [gitx/gitx#32]
What would I need to change in the code to enable GPG-signing I enjoy with command-line git?

**Comment by claybridges** [comment]
What's the git command line?

**Comment by andreif** [comment]
@claybridges Here is a guide https://github.com/pstadler/keybase-gpg-github

and an example of signed commit https://github.com/gitx/gitx/pull/34/commits

**Comment by andreif** [comment]
@claybridges ```git commit -S``` is probably what you are asking for

**Comment by andreif** [comment]
I think one would even love to see which commits are signed. I usually do that with `git log --pretty="format:%h %G? %aN  %s"` etc.

**Comment by claybridges** [comment]
Thanks for introducing a new concept to me.

**Comment by andreif** [comment]
@claybridges closed? wrong button? 😄

**Comment by claybridges** [comment]
Yep, wrong button, sorry.

**Comment by elia** [comment]
I think GitX already signs commits if it's enabled at config level (e.g. by `git config commit.gpgsign true`)

**Comment by andreif** [comment]
No, not for me at least

**Comment by nanotech** [comment]
GitX [uses git commit-tree](https://github.com/gitx/gitx/blob/8cf0f38876135eb00dfaac4d54b3fa50457911e1/Classes/git/PBGitIndex.m#L270) which [appears to only do signing when `-S` is set](https://github.com/git/git/blob/v2.11.1/builtin/commit-tree.c#L65).

Here's a small patch to add that, pending some configuration UI:

```diff
diff --git a/Classes/git/PBGitIndex.m b/Classes/git/PBGitIndex.m
index 77e65e6..fcf067d 100644
--- a/Classes/git/PBGitIndex.m
+++ b/Classes/git/PBGitIndex.m
@@ -273,6 +273,10 @@ - (void)commitWithMessage:(NSString *)commitMessage andVerify:(BOOL) doVerify
                [arguments addObject:@"-p"];
                [arguments addObject:parent];
        }
+       if (/* preference is set */ true) {
+               // commit-tree does not support the long --gpg-sign option for some reason
+               [arguments addObject:@"-S"];
+       }

        [self postCommitUpdate:@"Creating commit"];
        int ret = 1;
```

You'll also need to be using a graphical `gpg-agent` like [MacGPG/GPGTools](https://gpgtools.org/) and add `no-tty` to `~/.gnupg/gpg.conf` to tell `gpg` to not open `/dev/tty` (which doesn't exist in a GUI context). The latter could possibly be worked around by including a `gpg` wrapper script with GitX that adds `--no-tty` to its arguments, and pointing `git -c gpg.program=` at it.

**Comment by elia** [comment]
> No, not for me at least

my bad, I was looking at commits rebased from the CLI

**Comment by andreif** [comment]
@nanotech Would it be possible to incorporate the service part of GPGTools i.e. GPGServices? https://github.com/GPGTools/GPGServices
It would be great to do not require more software than for CLI git.

**Comment by andreif** [comment]
Sorry, I missed that it needs MacGPG, so I guess not so easy.

**Comment by andreif** [comment]
Their PR#1 is quite demotivating, 4.5 years, huh https://github.com/GPGTools/MacGPG2/pull/1

**Comment by andreif** [comment]
Currently:
* Merge creates a signed commit. 
* Cherry-pick tries to create a signed commit but fails due to gpg not found. I finish it in cli by `git commit`.
* Normal commit creates an unsigned commit.

**Comment by levinalex** [comment]
MacGPG does not seem to be required. I use:

```bash
$ cat ~/.gnupg/gpg-agent.conf 
pinentry-program /usr/local/bin/pinentry-mac
$ cat ~/.gnupg/gpg.conf      
no-tty
```

 (`brew install gnupg gpg-agent pinentry-mac`)

With the change by @nanotech, GitX asks me for the passphrase and signs my commits.

**Comment by mediafinger** [comment]
Thanks, good to know. :+1:

I assume there is no compiled and downloadable version yet?

**Comment by tiennou** [comment]
Not yet, sadly.

**Comment by taktran** [comment]
I followed these [instructions for using a custom bash script to sign git commands within gitx](https://josh.fail/blog/2019/signed-commits-with-gitx.html), and it works.

**Comment by jspiro** [comment]
I wasn't able to get this working, the script signs commits if I engage from the CLI, but not from gitx.

Let's fix it here! https://github.com/gitx/gitx/issues/206

**Comment by roopesh90** [comment]
Is anyone else looking around for this? or has probably found a solution?
