### ISSUE TITLE
Produces ZIPs for releases 

### ISSUE THREAD

**Issue by jvanzyl** [gitx/gitx#322]
Might it be possible to have ZIPs produced for the releases as well? I have an automated provisioning tool for laptops and ZIPs (or even tar.gz files) are easier to deal with.

I'm happy to contribute a PR if this is acceptable.

**Comment by claytonrcarter** [comment]
This sounds good to me, esp if you're willing to PR it. 😄 I think we would want to release DMGs *and* ZIPs, just to be clear. If that's doable, then 👍

**Comment by jvanzyl** [comment]
Great, I will work on a PR!

**Comment by jvanzyl** [comment]
Made a PR here: https://github.com/gitx/gitx/pull/323

I tried to build this in my fork, but the build failed. Not super familiar with the build but I'll try and find the issue. Not sure if it's simply from trying to build from a fork.

**Comment by jvanzyl** [comment]
Fix by [eb781a0](https://github.com/gitx/gitx/commit/eb781a08d5865f434dc34e1bcf347a3405998f98)

**Comment by jvanzyl** [comment]
I downloaded the ZIP file for x86_64 and I get the normal privacy warning but it works correctly.

**Comment by jvanzyl** [comment]
I downloaded the ZIP file for arm64 and I get the normal privacy warning but it works correctly as well.

**Comment by claytonrcarter** [comment]
Great! Thank you for the contribution!

**Comment by jvanzyl** [comment]
Might it be possible to do a release to make the ZIPs available?

**Comment by hannesa2** [comment]
> Might it be possible to do a release to make the ZIPs available?

Sure, I will do
