### ISSUE TITLE
Can't find app with identifier net.phere.GitX

### ISSUE THREAD

**Issue by amuraru** [gitx/gitx#336]
Trying to run the `gitx` CLI renders the following error in latest 0.22 release:
2022-09-19 14:45:32.247 gitx[37990:297844] Can't find app with identifier net.phere.GitX

**Comment by hannesa2** [comment]
What I've to do, to see this log entry ?

**Comment by janeklb** [comment]
If you download 0.22 release (I tested it with `...x64.dmg`), place it into your `/Applications/`, open it, then select "Enable Terminal Usage..." etc.

Then open up a terminal session and try to launch gitx (`gitx`), you should see this issue.

Interestingly, I'm able to launch it fine via Macos' Spotlight (cmd-space) or just by opening it from the finder.

**Comment by fredngo** [comment]
Yep... confirmed ☹️

**Comment by hannesa2** [comment]
> I've used `alias gitx='open -a GitX.app .'` to work around this problem on my machine.

Nice to have it. But not everyone should be forced to do so. 
I don't understand the root cause

**Comment by hannesa2** [comment]
> 

On my side I see first in `0.22` this 
<img width="251" alt="image" src="https://user-images.githubusercontent.com/3314607/191032610-ca4bd8e6-0244-4172-9257-b02856a100cb.png">

and when I enter gitx in terminal `0.21` will be opened. -confusioning-

**Comment by claytonrcarter** [comment]
There are still references to `net.phere.GitX` in the codebase: https://github.com/gitx/gitx/search?q=net.phere.GitX&type=code

I have not at all confirmed this, but I would suspect that the CLI command is trying do something like `open -a GitX.app .` but by finding the app w/ the old bundle ID. I wonder if updating all of the remaining references would fix this.

**Comment by janeklb** [comment]
> > 
> 
> On my side I see first in `0.22` this <img alt="image" width="251" src="https://user-images.githubusercontent.com/3314607/191032610-ca4bd8e6-0244-4172-9257-b02856a100cb.png">
> 
> and when I enter gitx in terminal `0.21` will be opened. -confusioning-

Could this be related to https://github.com/gitx/gitx/discussions/337 ?

**Comment by orendon** [comment]
I'm using the ARM64 release, the following error is shown when opening the `0.22` app through the terminal (CLI)
```
gitx[10725:1829513] Can't find app with identifier net.phere.GitX
```

Reverted to `0.21 arm64` and works just fine.

**Comment by insha** [comment]
> There are still references to `net.phere.GitX` in the codebase: https://github.com/gitx/gitx/search?q=net.phere.GitX&type=code
> 
> I have not at all confirmed this, but I would suspect that the CLI command is trying do something like `open -a GitX.app .` but by finding the app w/ the old bundle ID. I wonder if updating all of the remaining references would fix this.

@hannesa2 I concur with @claytonrcarter. This looks a like a side-effect of the notarized build. The `kGitXBundleIdentifier` in the `GitXScriptingConstants.h` should use the bundle identifier that is used for notarizing the app.

**Comment by hannesa2** [comment]
> There are still references to `net.phere.GitX` in the codebase: https://github.com/gitx/gitx/search?q=net.phere.GitX&type=code
> 
> I have not at all confirmed this, but I would suspect that the CLI command is trying do something like `open -a GitX.app .` but by finding the app w/ the old bundle ID. I wonder if updating all of the remaining references would fix this.

Any idea what identifier we should use here ?
Either we use `net.phere.GitX` for notarizing,
or we change all to an other (for me unknown) value

**Comment by insha** [comment]
The references in the code base should be fine, except for the `kGitXBundleIdentifier` constant in the `GitXScriptingConstants.h` file. It should be changed to the bundle identifier that is used for the notarization; which is `com.themacronaut.net.phere.GitX`.

**Comment by hannesa2** [comment]
Is there a benefit using `com.themacronaut.net.phere.GitX` instead of using previous `net.phere.GitX` ?

I made pre-release https://github.com/gitx/gitx/releases/tag/0.23-beta1 wich uses previous identifier `net.phere.GitX`
Please give it try and provide feedback. On my side it works properly

**Comment by insha** [comment]
The only reason for using the `com.themacronaut…` bundle identifier was for the notarization to work properly. That is because in order for me to create the Developer ID cert and provisioning profile, I also needed to create and App ID that was required for the provisioning profile. I couldn’t use the `net.pretend.GitX` bundle identifier because Apple won’t let me register and App ID for it. Which is why the change in the bundle identifier.

That said, is notarization is happening using the previous bundle identifier or the new one for build 0.23?

>

**Comment by hannesa2** [comment]
For `0.23-beta1` with `net.phere.GitX` you see [here](https://github.com/gitx/gitx/actions/runs/3087584303/jobs/4993103890) notarization looks not bad. I hope, that I can trust this output.
<img width="454" alt="image" src="https://user-images.githubusercontent.com/3314607/191260410-d7defaf3-9bf0-4fca-a575-e9a18bc5be18.png">

I'm not sure, when we use `com.themacronaut.net.phere.GitX` and do additional a global search/replace from  `net.phere.GitX` to `com.themacronaut.net.phere.GitX` will cause additional issues.

What should be do now ? Stay with `net.phere.GitX` or move to `com.themacronaut.net.phere.GitX` ?

**Comment by hannesa2** [comment]
I will build a beta2 with `com.themacronaut.net.phere.GitX`... let's see. Then we can decide.

**Comment by fcoury** [comment]
@hannesa2 this version worked fine for me.

**Comment by hannesa2** [comment]
Thanks for all the help !

Just for the records, I made https://github.com/gitx/gitx/releases/tag/0.23-beta2 which moved to `com.themacronaut.net.phere.GitX` and keep this unmerged.

I will merge `0.23-beta1` and keep `net.phere.GitX` I expect here less "surprises" and we can change this anytime.
