### ISSUE TITLE
Can't use gitx command line using latest version

### ISSUE THREAD

**Issue by fcoury** [gitx/gitx#338]
After installing latest version I am getting the following issue when trying to run it from the command line:

```
> $ gitx -v
GitX version 0.12

> $ gitx -c
2022-09-19 13:50:53.100 gitx[26153:2950878] -[SBScriptableApplication open:withOptions:]: unrecognized selector sent to instance 0x600003af1440
2022-09-19 13:50:53.100 gitx[26153:2950878] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[SBScriptableApplication open:withOptions:]: unrecognized selector sent to instance 0x600003af1440'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001a28f9198 __exceptionPreprocess + 240
	1   libobjc.A.dylib                     0x00000001a2643e04 objc_exception_throw + 60
	2   CoreFoundation                      0x00000001a298cf40 -[NSObject(NSObject) __retain_OA] + 0
	3   CoreFoundation                      0x00000001a2858544 ___forwarding___ + 1764
	4   CoreFoundation                      0x00000001a2857da0 _CF_forwarding_prep_0 + 96
	5   gitx                                0x00000001026995fc gitx + 5628
	6   gitx                                0x000000010269a4e0 gitx + 9440
	7   dyld                                0x00000001026bd08c start + 520
)
libc++abi: terminating with uncaught exception of type NSException
```

```
> $ ls -la `which gitx`
lrwxr-xr-x  1 root  wheel  46 Sep 19 13:56 /usr/local/bin/gitx -> /Applications/GitX.app/Contents/Resources/gitx

> $ /Applications/GitX.app/Contents/Resources/gitx -v
GitX version 0.12
```

![image](https://user-images.githubusercontent.com/1371/191071264-28c07de8-607c-4978-952e-dfea2af4f75a.png)

![image](https://user-images.githubusercontent.com/1371/191072128-4456066e-54f5-47f9-932a-1bd7f6719348.png)

Things I tried:

- I have reinstalled the terminal usage from 0.22
- I have manually removed the gitx executable and installed terminal usage again
- I have tried both the arm64 and x86 versions and both report the same issue
- Reverting to 0.21 works fine.

**Comment by fcoury** [comment]
![image](https://user-images.githubusercontent.com/1371/191071264-28c07de8-607c-4978-952e-dfea2af4f75a.png)

**Comment by hannesa2** [comment]
I set `0.22` as pre-release to avoid to have it on prominent position.
I hope someone will understand what's wrong here, the biggest suspect is #334

**Comment by fcoury** [comment]
Thanks @hannesa2 and if you need more info from me, I'll be glad to provide it.

**Comment by hannesa2** [comment]
This us the same like #336

I made pre-release https://github.com/gitx/gitx/releases/tag/0.23-beta1 wich uses previous identifier `net.phere.GitX`
Please give it try and provide feedback. On my side it works properly

**Comment by fcoury** [comment]
@hannesa2 this new version works fine!

**Comment by hannesa2** [comment]
https://github.com/gitx/gitx/issues/336#issuecomment-1252428904
