### ISSUE TITLE
v0.22 & v0.23 don't work [solved]

### ISSUE THREAD

**Issue by jillesvangurp** [gitx/gitx#342]
v0.23 is broken for me (M1 macbook pro).

The last working version for me is v0.21

Here are the error messages I'm getting.

v0.23:

```
➜  ✗ gitx
2022-09-20 17:07:59.328 gitx[18212:82675363] warning: failed to get scripting definition from /Applications/GitX.app/Contents/Frameworks/Sparkle.framework/Versions/B/Updater.app; it may not be scriptable.
2022-09-20 17:07:59.328 gitx[18212:82675363] -[SBApplication open:withOptions:]: unrecognized selector sent to instance 0x600002e31560
2022-09-20 17:07:59.336 gitx[18212:82675363] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[SBApplication open:withOptions:]: unrecognized selector sent to instance 0x600002e31560'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000196ecd1a8 __exceptionPreprocess + 240
	1   libobjc.A.dylib                     0x0000000196c17e04 objc_exception_throw + 60
	2   CoreFoundation                      0x0000000196f60f4c -[NSObject(NSObject) __retain_OA] + 0
	3   CoreFoundation                      0x0000000196e2c554 ___forwarding___ + 1764
	4   CoreFoundation                      0x0000000196e2bdb0 _CF_forwarding_prep_0 + 96
	5   gitx                                0x0000000104afd60c gitx + 5644
	6   gitx                                0x0000000104afe4f0 gitx + 9456
	7   dyld                                0x0000000104da108c start + 520
```

v0.22:

```
gitx
2022-09-20 17:09:35.243 gitx[18330:82676955] Can't find app with identifier net.phere.GitX
```

**Comment by hannesa2** [comment]
Anyone else ? On my side it works properly 
<img width="278" alt="image" src="https://user-images.githubusercontent.com/3314607/191321426-9ae3b9f4-14bf-436b-abeb-f672a70b6dc1.png">
Btw, I see we should add architecture in this version info.

**Comment by orendon** [comment]
Same here for `arm64` release

**Comment by hannesa2** [comment]
I can't reproduce it, so an other guy should look into this.

**Comment by jillesvangurp** [comment]
getting the same error as on v0.23 with that version.

**Comment by janeklb** [comment]
I'm also getting the same error with v0.23 (Intel / amd64 build). But.. if gitx is already running / if i've launched from the finder, then `gitx` from the terminal works fine.

Interesting side note that might help with diagnosing the problem: running `gitx --version` produces
```shell
GitX version 0.12
```

Furthermore this (as well as `gitx --help`) **works fine** from the terminal even if GitX is not already running.

**Comment by hannesa2** [comment]
> I'm also getting the same error with v0.23 (Intel / amd64 build). But.. if gitx is already running / if I've launched from the finder, then gitx from the terminal works fine.

Hm, on my side both scenarios are working properly, independent if it's already started or not. 
I hope you installed "_Enable terminal usage.._." again. I at least did it.

> Interesting side note that might help with diagnosing the problem: running gitx --version produces

I see, we don't update version here, just in _About_ 
<img width="703" alt="image" src="https://user-images.githubusercontent.com/3314607/191607638-dcd55aa0-7b34-4f95-8840-4257f0328c32.png">

For me it's still not clear, what's the diff on your side. Without understanding the issue, I'm not sure if I can help here. 
Btw, I'm definitely no macOS/Xcode developer with deep knowledge. But i can merge any working pull request.

**Comment by jillesvangurp** [comment]
OK that indeed explains it. I installed the new version but always launch it from the command line, which still points to the old installation.

just to confirm the fix

1. update your gitx by dragging the new version to `/Applications'
2. run it from the command line, it will fail because that still points to the old version
3. launch from the finder, this indeed works
4. re-install the terminal integration
5. quit
6. launch it from the command line by typing `gitx`. This should now work fine now

**Comment by jillesvangurp** [comment]
So, you can close this. But you might want the error less obscure or document how to resolve it.

**Comment by hannesa2** [comment]
Nice, the reason is found.
This caused from error prone `0.22` and I know a manual step will often not done, even a documentation will be not read.
Best would be an automated step, but I've no idea how **WE** could detect the need of this password-required step.

To be honest, when I would run into this issue, I would start to search and hopefully find this issue with caption "closed". At least for me, this is the best solution.
