### ISSUE TITLE
GUI glitches on High Sierra

### ISSUE THREAD

**Issue by elosha** [gitx/gitx#348]
Hey, just went form 0.19 to 0.23 and noticed a few GUI glitches.

a) Option buttons (?) in top/bottom toolbars are missing their end on the right side
![gitx023_toolbar-top_highsierra](https://user-images.githubusercontent.com/30213185/201617410-cefab11a-06ec-48cf-b9b4-ad34fb0d4884.png)

b) The status bar is also missing its top border across its whole width
![gitx023_toolbar-bottom_highsierra](https://user-images.githubusercontent.com/30213185/201617366-b521b361-cdd0-47a5-8aba-ad7aa6a1da7a.png)
Note: On Monterey, the status bar in Finder has a top border, so count it as a general glitch.

Otherwise everything looks fine as always – but will let you know here should I find more. :)

**Comment by hannesa2** [comment]
Thanks for your report. We also need some helping hands with pull request

**Comment by elosha** [comment]
Are you referencing PR https://github.com/gitx/gitx/pull/96 ?

**Comment by hannesa2** [comment]
Not really, I joined in 2020 to make it work on M1 and keep project alive as good as I can. I'm **no** Objective C developer

**Comment by elosha** [comment]
Confirming fixed on High Sierra!
![highsierra](https://user-images.githubusercontent.com/30213185/201891098-94b36849-f39f-421f-894a-e18f0b5fc21b.png)

**Comment by elosha** [comment]
I have to work over the Commit view. "Commit" button crashing into the status bar. Bugfix for this is almost ready, just need to filter Xcode's automatic changes from my bugfix commit.
