### ISSUE TITLE
"Gist it" appears despite disabled in settings

### ISSUE THREAD

**Issue by elosha** [gitx/gitx#355]
The "Gist it" button appears in commit view even when "Enable 'Gist it'" is inactive in app settings.

Version: 0.23
Mac OS: 10.13.x and 12.x

May have at it look later …

**Comment by ADTC** [comment]
Adding screenshot:
<img width="515" alt="image" src="https://user-images.githubusercontent.com/6047296/221338194-64a2fafb-a5e0-4a3e-83e5-ccc1bbca6257.png">
