### ISSUE TITLE
DMG file has no shortcut to Applications

### ISSUE THREAD

**Issue by ADTC** [gitx/gitx#362]
It seems that the DMG file (when mounted as a disk) doesn't have any shortcut included for Applications. Usually DMG files include one so I'd just drag the `.app` file into the Applications shortcut to copy it into my Applications folder.

I have tried the `arm64` version as I'm on Apple Silicon. I'm not sure if it's a problem specific to this version. (Note for the screenshot below: I have made file extensions visible.)

<img width="920" alt="image" src="https://user-images.githubusercontent.com/6047296/221337785-80433cf0-a4da-4b4c-8812-48087792687f.png">

----
_Thank you for this tool. This is my first issue here, and I think I may contribute more issues or doc PR. I hope we can increase exposure of this because Google search for GitX still shows the old two versions (the original and the fork) above this one._

**Comment by hannesa2** [comment]
> Thank you for this tool. This is my first issue here, and I think I may contribute more issues or doc PR. I hope we can increase exposure of this because Google search for GitX still shows the old two versions (the original and the fork) above this one.

Nice, when you help us to improve the tool.

**Comment by ADTC** [comment]
I would love to! Unfortunately I have no Objective-C experience right now, and my last experience with C/C++ in general was like two decades ago. 😂 I'll see what I can do. (I saw issue #66 about Swift migration.)
