### ISSUE TITLE
Commit pickaxe search is not working

### ISSUE THREAD

**Issue by andreif** [gitx/gitx#37]
Could you confirm the issue? Is there a good way to debug why it's not working for me?

**Comment by nanotech** [comment]
It works for me on the gitx repo. gitx [shells out to `git log`][0] to do the pickaxe and path searches, so try running `git log -Ssearchterms` or `git log --pickaxe-regex searchterms` from a terminal.

[0]: https://github.com/gitx/gitx/blob/8d085386c3d654cc490fe10243ee7147f8ae885f/Classes/Controllers/PBHistorySearchController.m#L409-L424

**Comment by andreif** [comment]
It worked for me in last `GitX (R)` version, but not in compiled `GitX-dev` master.

**Comment by andreif** [comment]
So if it does not work just for me, could you guide me how I can debug the code? `git log` works fine.

**Comment by andreif** [comment]
GitX search does nothing for me, no noticeable reaction to enter.

**Comment by bhaak** [comment]
None of the searches works for me with master. I bisected it down to commit dddc3e9 as the culprit.

**Comment by nanotech** [comment]
Thanks for bisecting @bhaak. I must have been using an old build before because I can reproduce now. Whoops.

I opened #41 to fix this.
