### ISSUE TITLE
Automate howebrew publish

### ISSUE THREAD

**Issue by hannesa2** [gitx/gitx#372]
As followup of #284 we should automate the publish process to homebrew during release.
The process should update these values 
https://github.com/Homebrew/homebrew-cask/blob/9d9bc236a1f2ba17633f28a9f6680627842b4810/Casks/gitx.rb#L4-L6

This action is promising https://github.com/marketplace/actions/homebrew-releaser but there are a lot of required fields, which I currently don't know how to fill. eg. `install: 'bin.install "gitx"'`

**Comment by claytonrcarter** [comment]
*Fair warning: I don't actually know what I'm talking about here; this is just speculation and educated guessing.*

If I understand correctly, [homebrew-releaser](https://github.com/marketplace/actions/homebrew-releaser) seems aimed at making releases to custom maintained taps. The gitx cask is not our own, though, it's part of the official homebrew casks. I think that this might be more relevant: https://github.com/marketplace/actions/homebrew-bump-cask (I haven't tried it, but it looks easier to set up, and includes an example.)

Other related reading that I turned up:
- Official way to update manually: https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request#submit-a-new-version-of-an-existing-cask
- More on updating manually: https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask
- Example: https://openrefine.org/docs/technical-reference/homebrew-cask-process

**Comment by hannesa2** [comment]
Done with https://github.com/gitx/gitx/pull/395
