### ISSUE TITLE
Broken UI on master

### ISSUE THREAD

**Issue by tiennou** [gitx/gitx#382]
After a bunch of bisecting around, I can confirm that since 322e12284152e0787ad3d81e554b191d902454af went in, the UI looks like this:

<img width="1792" alt="borken-gitx" src="https://user-images.githubusercontent.com/81099/222182530-55a1a175-6824-40f5-9df4-f021b8ea2608.png">

@elosha Can you maybe have a look? I'm pretty sure it's the maxWidth <= 300 constraint you've added, but dynamic layout isn't my strong point.

**EDIT** Since it's likely relevant, this is on macOS 13.2.

**Comment by elosha** [comment]
@tiennou Thanks for the hint. I'd say better revert that commit (it's just the .xibs).

And I'll figure out how to fix the original display bug without Interface Builder messing up lots of other stuff. Probably I need to edit the files manually.

**Comment by tiennou** [comment]
Okay, I'll file that then 👍.

To be honest the whole view controller stack in here needs to be shot and rebuilt using more modern things (we didn't have even `NSViewController` at the time), but I lack guidance as to what's the best architecture to go for. Right now I'm trying to shove the 3 main controllers into the main window XIB and see if it works.

**Comment by ADTC** [comment]
I'm experiencing serious bugs in this UI actually. It's practically unusable for me, because it doesn't reflect the state of the repository properly. Hope we can fix it soon. Also, would be nice to see all diff together, same as commit diff (i.e. not each file one by one). Maybe we can re-think this UI to be more intuitive. Do I have the liberty?

**Comment by tiennou** [comment]
To be honest, I have a load of in-progress, not finished stuff (I noticed a commit from 2015 labeled "Fix a bug where NEW files couldn't be unstaged"), as well as trying to rewire everything to go through `libgit2` instead. I can file up the branches now that I managed to bring them up to speed (thanks to `git-assembler`), if you want to have a look?

**Comment by tiennou** [comment]
About the specific points you made, I'm aware there are quite a few issues with how the low-level index gets updated:
- A new, untracked file seen once can never be removed from the untracked list. You have to restart GitX (that's the one that that one commit I alluded to should fix).
- A new untracked file that gets staged and commited never shows a diff (I think that's what #370 is about). Again, that needs a restart.
- No support for conflicts. GitX errors if you try to stage a hunk from a conflicted file, so you have to start with staging/unstaging the whole file before attempting that.
- Staging a couple of hunks then unstaging the whole file afterward doesn't work, as the manually staged hunks will stay staged until you unstage them manually.
- Amending a merge commit breaks it and leaves only one parent.

About the UI itself, I don't really have an opinion ? I like how having it split up like that keeps it snappy — I frequently have to navigate through commits in the history view which have `package.lock` files, and since you can only "snip" the whole diff, if by sheer unluckiness the file you're interested in is after the huge diff you'll get a good slowdown.
