### ISSUE TITLE
I dont want dark model. How can I switch light theme

### ISSUE THREAD

**Issue by LiJohnson** [gitx/gitx#389]
I do not like this , and there is not button in prefrences menu to turn it off
<img width="943" alt="image" src="https://user-images.githubusercontent.com/2616788/224075734-a207669c-8afa-4249-bae9-9bc215bcd847.png">

**Comment by hannesa2** [comment]
My is light out of the box 
<img width="460" alt="image" src="https://user-images.githubusercontent.com/3314607/224083973-9415b4c2-629a-493d-b6a4-25b0e74db635.png">
It relay on your machine settings.
<img width="471" alt="image" src="https://user-images.githubusercontent.com/3314607/224084174-f73e3370-1f90-4482-81cc-bdb4162a6408.png">

**Comment by LiJohnson** [comment]
I hope to switch it standlone ,like this 
<img width="410" alt="image" src="https://user-images.githubusercontent.com/2616788/224086970-82ae9b64-77e6-4ebe-b7d1-8f76a6c1a408.png">
😶‍🌫️ 😶‍🌫️ 😶‍🌫️
