### ISSUE TITLE
clang: error: no such file or directory: 'External/libssh2.a' clang: error: no such file or directory: 'External/libcrypto.a'

### ISSUE THREAD

**Issue by tian-xiaobo** [gitx/gitx#405]
Ld /Users/linux/Library/Developer/Xcode/DerivedData/GitX-gibjuckxmdmmkldlynhieuwemmsz/Build/Intermediates.noindex/ObjectiveGitFramework.build/Debug/ObjectiveGit-Mac.build/Objects-normal/x86_64/Binary/ObjectiveGit normal x86_64 (in target 'ObjectiveGit-Mac' from project 'ObjectiveGitFramework')
    cd /Users/linux/workspace/gitx/External/objective-git
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target x86_64-apple-macos10.9 -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk -L/Users/linux/Library/Developer/Xcode/DerivedData/GitX-gibjuckxmdmmkldlynhieuwemmsz/Build/Products/Debug -L. -LExternal -L/Users/linux/workspace/gitx/External/objective-git/External/build/lib -F/Users/linux/Library/Developer/Xcode/DerivedData/GitX-gibjuckxmdmmkldlynhieuwemmsz/Build/Products/Debug -filelist /Users/linux/Library/Developer/Xcode/DerivedData/GitX-gibjuckxmdmmkldlynhieuwemmsz/Build/Intermediates.noindex/ObjectiveGitFramework.build/Debug/ObjectiveGit-Mac.build/Objects-normal/x86_64/ObjectiveGit.LinkFileList -install_name @rpath/ObjectiveGit.framework/ObjectiveGit -Xlinker -rpath -Xlinker @loader_path/Frameworks -Xlinker -rpath -Xlinker @executable_path/../Frameworks -Xlinker -object_path_lto -Xlinker /Users/linux/Library/Developer/Xcode/DerivedData/GitX-gibjuckxmdmmkldlynhieuwemmsz/Build/Intermediates.noindex/ObjectiveGitFramework.build/Debug/ObjectiveGit-Mac.build/Objects-normal/x86_64/ObjectiveGit_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -fobjc-arc -fobjc-link-runtime -fapplication-extension -force_load External/libgit2.a External/libssh2.a External/libcrypto.a -lz -liconv -lgit2 -framework Cocoa -compatibility_version 1 -current_version 1 -Xlinker -dependency_info -Xlinker /Users/linux/Library/Developer/Xcode/DerivedData/GitX-gibjuckxmdmmkldlynhieuwemmsz/Build/Intermediates.noindex/ObjectiveGitFramework.build/Debug/ObjectiveGit-Mac.build/Objects-normal/x86_64/ObjectiveGit_dependency_info.dat -o /Users/linux/Library/Developer/Xcode/DerivedData/GitX-gibjuckxmdmmkldlynhieuwemmsz/Build/Intermediates.noindex/ObjectiveGitFramework.build/Debug/ObjectiveGit-Mac.build/Objects-normal/x86_64/Binary/ObjectiveGit

clang: error: no such file or directory: 'External/libssh2.a'
clang: error: no such file or directory: 'External/libcrypto.a'
Command Ld failed with a nonzero exit code

**Comment by hannesa2** [comment]
I'm not sure what you exactly did, I miss the commands. 
Please check out https://github.com/gitx/gitx/blob/master/.github/workflows/BuildPR.yml#L64-L67 how to build it

**Comment by hannesa2** [comment]
Please reopen, if it doesn't help

**Comment by peterwillcn** [comment]
> I'm not sure what you exactly did, I miss the commands. Please check out https://github.com/gitx/gitx/blob/master/.github/workflows/BuildPR.yml#L64-L67 how to build it

@hannesa2 Very helpful, cd External/objective git&&script/bootstrap successfully compiled. Thank you very much, great！
