### ISSUE TITLE
Apple notary is broken

### ISSUE THREAD

**Issue by hannesa2** [gitx/gitx#415]
> A required agreement is missing or has expired. This request requires an in-effect agreement that has not been signed or has expired

![image](https://github.com/gitx/gitx/assets/3314607/57564b44-15b3-421b-ab57-ea0630f8532d)

https://github.com/gitx/gitx/actions/runs/6205528550/job/16848803936?pr=414

It looks like something is expired.

@insha as you are the noble sponsor of our notary, I would love, if you can have a view on it. Thank you !

**Comment by insha** [comment]
On it. Let me see what is Apple complaining about.

**Comment by insha** [comment]
All right. I have accepted and signed all agreements from Apple and this issue should be resolved. Please give it another go and let me know if it is still failing.

**Comment by hannesa2** [comment]
Thank you ! This issue works now properly again.
