### ISSUE TITLE
Build x86 is broken

### ISSUE THREAD

**Issue by hannesa2** [gitx/gitx#418]
I observe a broken x86 build on CI #414 and with my limited XCode knowledge, I even don't understand what's wrong here.
Arm64 build works properly. 
Who can help me here ?

**Comment by insha** [comment]
Seeing the following in the logs from the `build-gitx (Xcode_13.3, macos-12, x86_64)` and `build-gitx (Xcode_14.1.0, macos-12, x86_64)` actions:
```
Undefined symbols for architecture x86_64:
"_EVP_PKEY_get_id", referenced from:
  __libssh2_ed25519_new_private_frommemory in libssh2.a(crypto.o)
  __libssh2_pub_priv_keyfile in libssh2.a(crypto.o)
  __libssh2_pub_priv_keyfilememory in libssh2.a(crypto.o)
ld: symbol(s) not found for architecture x86_64
```

My guess is that either a file is missing/not included for `libssh2` where these symbols are defined or that the `libssh2` may not have been built for x86_64 architecture.

**Comment by hannesa2** [comment]
Right, but I changed here nothing and all pull request were merged only with properly positive build state.
For me it looks like, it's either the runner (probably not) or https://github.com/gitx/objective-git/blob/d872ee901116d5bab1813ab62e56d1bfa475dc3c/script/bootstrap#L12 during prepare build machine.

Unfortunately the log files are no more there on last successful build to investigate used version
<img width="1033" alt="image" src="https://github.com/gitx/gitx/assets/3314607/07dd3743-9f1e-467e-b1de-9a54b6cf6d1b">

**Comment by hannesa2** [comment]
@insha You mean it happens on libssh2 update on github runner machine ?
This is the current situation on runner 
<img width="572" alt="image" src="https://github.com/gitx/gitx/assets/3314607/f7074cb7-ced0-49eb-bd21-d03a2016daec">

Do you have an idea to make it work ?

**Comment by insha** [comment]
>@insha You mean it happens on libssh2 update on github runner machine ?

I didn't try it on the runner, but it happened on another machine of mine that had a slightly newer version of `libssh2` than the one in your screenshot.

> Do you have an idea to make it work ?

I think since these are dependencies, there are couple of options: 
1. We could use pre-built libs for Objective-Git for both X86_64 and Apple Silicon, instead of building them every time.
2. Pin the versions for the Objective-Git dependencies to versions that we know work, that way only those versions are used. I am not sure of the feasibility of this in the context of a runner.

There is work involved for both options, but I believe doing either one will give us a deterministic build every time.

**Comment by hannesa2** [comment]
@insha I see on self hosted arm64 runner
`OpenSSL 3.2.0 23 Nov 2023 (Library: OpenSSL 3.2.0 23 Nov 2023)`
and on github runner x86 runner
`OpenSSL 1.1.1w  11 Sep 2023`

**Comment by hannesa2** [comment]
I'm fighting with a fix for x86.
I'm close to drop x86 support because nobody is interested https://github.com/gitx/gitx/discussions/419

**Comment by claytonrcarter** [comment]
Before we set up the CI builds, I recall Homebrew constantly trying to install OpenSSL 1.1.1 and that causing GitX to break because it needed 1.0.8 (or whatever the last 1.0.x was). Perhaps that was just a linking issue, but I recall being suspicious of 1.1.1

**Comment by hannesa2** [comment]
When I use openssl@3 I run into this https://github.com/gitx/gitx/actions/runs/7275256054/job/19822819390

Brew doesn't have openssl@1.0.x anymore.
<img width="809" alt="image" src="https://github.com/gitx/gitx/assets/3314607/cb5c65ea-25d5-4caa-8079-e0ef150aef60">

When I use an other way to use openssl@1.0.1 I run into this https://github.com/gitx/gitx/actions/runs/7275249630/job/19822799986

I give up now. When the next release will come (no clue when) and x86 was not fixed by someone, I will skip x86 for the next release.

**Comment by insha** [comment]
@hannesa2 One other option is to move objective-git and all its dependencies into a Swift package using `xcframework` that can provide binaries for multiple architectures. This would greatly help updating, creating builds, and I am hoping contributions to this project. I recall this is being done on another project (OSS), so let me find out where I saw it and I will share my findings here.

**Comment by hannesa2** [comment]
thanks to @chrisirhc it's fixed https://github.com/gitx/gitx/pull/437
