### ISSUE TITLE
Update the readme with correct build instructions (rather than it being buried in a 15 month old issue)

### ISSUE THREAD

**Issue by justincbeck** [gitx/gitx#454]
The GH issues I've looked at have different versions of instructions for building the application. It seems like none of them are correct. It would be great if the README actually just contained the correct instructions either through XCode or via the CLI.

**Comment by hannesa2** [comment]
Which instruction do you mean ? I'll remove obsolete instructions, if there are some left.
In my point of view a running pull request pipeline is the best documentation

**Comment by justincbeck** [comment]
Well, on my M3 MBP the instructions that I _did_ find didn't work due to missing files or some such. So, unfortunately, I am unable to build the application. I am, however, running version 1. So, it sounds like that's the best option for now.
