### ISSUE TITLE
Show that files were moved

### ISSUE THREAD

**Issue by andreif** [gitx/gitx#46]
*Git-X(R)* shows that files were relocated:

<img src="http://i.imgur.com/VsD6MQ5.png" width=300>

and *GitX-dev* is not doing it anymore:

<img src="http://i.imgur.com/4TQM3qj.png" width=200>

It would be great to restore such visualization.

**Comment by claybridges** [comment]
I support this. But what is `Git-X(R)`? And I believe we are now `GitX(N)`.

**Comment by ssp** [comment]
looking into it – it seems like this was introduced when GitX switched from using the CLI to create the diffs to using a library

**Comment by andreif** [comment]
@claybridges Huh, I was always thinking that [rowanj fork](https://rowanj.github.io/gitx/) was called _GitX(R)_ similar to [_GitX(L)_](http://gitx.laullon.com) but that's just because I called it so long time ago on my mac 😄. There is #34 to change the name to _GitX(N)_ but I haven't got any feedback on it yet...
