### ISSUE TITLE
List of enhancements

### ISSUE THREAD

**Issue by andrebraga** [gitx/gitx#6]
Hello!

I'm extremely glad you people teamed up to further develop GitX, and I hope I can be part as well, as soon as I return from an ongoing business trip.

I have been using SourceTree for like forever and there are several shortcomings to it, but there are some stuff it does well. And stuff it's terrible at. And there's missing functionality.

I propose making a wishlist. We can then prioritise the items and set milestones.

- [ ] Soft/mixed resetting a branch.
- [ ] Interactive rebase.
- [ ] Integrated (3-way) merging of conflicts.
- [ ] Edit remotes.
- [ ] Manage submodules.
- [ ] Manage subtrees.
- [ ] Nicer handling of stashes.
- [ ] Commit message templates.
- [ ] LFS support.
- [ ] Repository bookmarks (other than the initial window, or a souped up version of it accessible at any time).
- [ ] Generate a zip archive out of a commit.
- [ ] Picking/discarding chunks from a stash instead of whole-deal push/pop.

Thanks!

**Comment by rjmunro** [comment]
Resetting a branch is already done by GitX in the best way of any Git UI I have ever seen. You can just drag branches around in the tree view and reset them to wherever you want.

**Comment by andrebraga** [comment]
I tried emulating your suggestion and couldn't really reproduce it. Mind dumbing it down for me? :sweat_smile:

**Comment by tiennou** [comment]
@andrebraga long-click on a non-checkedout branch (green labeled), get shadowy label, drop on commit list

**Comment by andrebraga** [comment]
I'm feeling a bit stupid right now but I still can't do it. I did try the obvious variations. I surely am embarrassing myself here but... I can initiate the drag but I can't seem to validly drop it anywhere on the window.

**Comment by rjmunro** [comment]
I think it's actually doing something like `git branch -f [branch name] [commit]`, which is IMHO more useful than resetting. Reset --soft is handy sometimes, however.

**Comment by rjmunro** [comment]
Would it not be better to split these into one issue each? Someone in the organisation can then give them all an "enhancement" label, and we could vote on them with the reaction buttons.

**Comment by andrebraga** [comment]
Consider this a brainstorming list, then we split it into proper issues.

**Comment by tiennou** [comment]
@rjmunro 👍 I too fear this would become a nasty mess of intertwined comments. I've already refrained from saying anything because of that 😉. I'll close this, feel free to reopen separate issues for each of those and I'll gladly triage !
