### ISSUE TITLE
Branches prefixed with @ freak out GitX

### ISSUE THREAD

**Issue by claybridges** [gitx/gitx#63]
Sometimes I will create a branch prefixed with an @ sign, e.g. `@this-branch`. `git` has no problem with these, but GitX puts them into the OTHER category:
![at-sign-branch](https://cloud.githubusercontent.com/assets/96004/23559673/bcdfac50-0005-11e7-9dde-80cea9649537.png)

Also, when these branches are checked out, GitX seems to hide certain remotes branches and/or other behavior I haven't completely nailed down yet.

**Comment by rjmunro** [comment]
Using greenkeeper.io in a typescript project, I frequently had branches with names like greenkeeper/@types/foo, which does the same thing, as does any branch with an @ sign anywhere in it's name.

**Comment by claybridges** [comment]
FWIW, I first pull requested a fix for this in July 2013 on GitX-dev: https://github.com/rowanj/gitx/pull/234.
