### ISSUE TITLE
Fresh release?

### ISSUE THREAD

**Issue by jakirkham** [gitx/gitx#64]
Was wondering if there was a new release planned. Noting that there are some logistics still being sorted out ( https://github.com/gitx/gitx/issues/18 ) ( https://github.com/gitx/gitx/issues/38 ). Still would be great to get a clear idea on what timeline we are looking at.

**Comment by jakirkham** [comment]
Just wanted to check in and see if there was any news on this front. Is there a release scheduled?

**Comment by jakirkham** [comment]
Any news?

**Comment by tiennou** [comment]
Well, we're mostly there 😉. I'm closing this in favor of the umbrella issue, which is #38.
