### ISSUE TITLE
Build failed during code signing, key not found.

### ISSUE THREAD

**Issue by akerfoot** [gitx/gitx#72]
Hi,

I tried to build gitx via the instructions here: https://github.com/gitx/gitx/wiki/Build-instructions

I ran into this error:

```
$ Scripts/build.py build release
mvers: ${CURRENT_PROJECT_VERSION}
vers:  0.12
Setting CFBundleShortVersionString of project GitX to: 
    0.15.2242 dev.

Updating CFBundleShortVersionString in Info.plist(s)...

Updated CFBundleShortVersionString in "GitX.xcodeproj/../Resources/Info-gitx.plist" to 0.15.2242 dev
Updated CFBundleShortVersionString in "GitX.xcodeproj/../Resources/Info.plist" to 0.15.2242 dev
Setting version of project GitX to: 
    0.15.2242.

Also setting CFBundleVersion key (assuming it exists)

Updating CFBundleVersion in Info.plist(s)...

Updated CFBundleVersion in "GitX.xcodeproj/../Resources/Info-gitx.plist" to 0.15.2242
Updated CFBundleVersion in "GitX.xcodeproj/../Resources/Info.plist" to 0.15.2242



The following commands produced analyzer issues:
	AnalyzeShallow Classes/Views/GitXTextFieldCell.m
(1 command with analyzer issues)
Signing MGScopeBar.framework
error: The specified item could not be found in the keychain.
Signing ObjectiveGit.framework
error: The specified item could not be found in the keychain.
Signing Sparkle.framework
error: The specified item could not be found in the keychain.
Signing gitx
error: The specified item could not be found in the keychain.
Signing gitx_askpasswd
error: The specified item could not be found in the keychain.
Signing GitX.app
error: The specified item could not be found in the keychain.
.......................................................................................
created: /<path>/gitx/build/Release/GitX-dev-2242.dmg
Error opening key file /<path>/gitx/updates/gitx-updates.key
20817:error:02001002:system library:fopen:No such file or directory:/BuildRoot/Library/Caches/com.apple.xbs/Sources/OpenSSL098/OpenSSL098-64.30.2/src/crypto/bio/bss_file.c:356:fopen('/<path>/gitx/updates/gitx-updates.key','r')
20817:error:20074002:BIO routines:FILE_CTRL:system lib:/BuildRoot/Library/Caches/com.apple.xbs/Sources/OpenSSL098/OpenSSL098-64.30.2/src/crypto/bio/bss_file.c:358:
unable to load key file
```

This was building master, commit `0633fbbcd342bac6a3b60d74a9b2829b4abbf6d7` on OS X 10.12.3.

There was no `gitx-updates.key` file at that location.

I'm not familiar with the code signing process, so I don't really think I can offer more insight. Please let me know if you need any more info.

**Comment by tiennou** [comment]
That Wiki page talks about doing a "real" release (package DMGs, update appcasts, stuff). You'd be better off just launching Xcode, build the GitX target, and stash the resulting product somewhere (or alternatively `Scripts/build.py build debug`).

Sorry about that slightly misleading page, we're still in the process of cleaning up some loose ends.

**Comment by akerfoot** [comment]
Thanks! Both those methods worked.

**Comment by claybridges** [comment]
Should we consider this a bug and leave it around, so it doesn't keep getting reported?

**Comment by elia** [comment]
[This wiki update should help](https://github.com/gitx/gitx/wiki/Build-instructions/_compare/6ca70e47df98cbfafc3144f50fffc6a163a423ec...599eec685cd157edac98d712bd44f4efac118989) clarify things for the casual contributor

**Comment by tiennou** [comment]
@beporter Relevant issues for your build failure. HTH !

**Comment by beporter** [comment]
Cross referencing my solution comment: https://github.com/gitx/gitx/issues/94#issuecomment-314164862
