### ISSUE TITLE
Fix the stash/discard/copy buttons

### ISSUE THREAD

**Issue by tiennou** [gitx/gitx#9]
This

![capture d ecran 2016-12-20 10 04 00](https://cloud.githubusercontent.com/assets/81099/21344360/bc7a5b64-c69b-11e6-822a-41d369caaee2.PNG)

makes me nervous.

I know I'll misclick once, and lose stuff. I know.

Propostions :
- Standardize on an ordering. Easy to do, but breaks muscle memory.
- Remove Copy, and make it go through the responder chain, as it should have. Harder, esp. w.r.t the state of the chain, but less UI clutter, and misclick chance gets `NULL`ed.

**Comment by ssp** [comment]
As the Discard Button will ask for confirmation before destroying your work, you probably won’t lose stuff all that easily :)

Yet I totally agree with your point that a standardised ordering will definitely make a better UI.

I totally like the idea of moving the copy command and reducing the clutter (but at this point I am not familiar enough with GitX’s WebKit integration to know how to make this work).

**Comment by nanotech** [comment]
Yeah, keeping the order consistent is much better. I noticed this too while I was restyling but didn't get to looking closer at it.

I just created #11 which connects copying to the responder chain. `WebView` has some APIs that make it pretty easy.
