### ISSUE TITLE
move to trash!!

### ISSUE THREAD

**Issue by pvinis** [gitx/gitx#98]
hello.
`move to trash` should ask for confirmation. heres why.

i have some changes in a file. if i try to discard these changes, i get asked if im sure. if i accidentally click on to move it to trash, then all my changes go away with it. thats not right, is it..

**Comment by tiennou** [comment]
Moving to trash doesn't lose changes, it just moves the file to the trash. So "all [your] changes go away with it" is only somewhat correct : if you restore the file, your changes are still in there.

Semantics aside, it seems there's a bug w.r.t to that dialog box : I'm pretty sure I have been asked for confirmation, but now I don't.

**Comment by pvinis** [comment]
well yea the changes stay in the file, but to restore the file I have to manually go to the trash and restore. I should not need to go away from the app to do that.

yes, a confirmation dialog would be nice.

**Comment by tiennou** [comment]
> well yea the changes stay in the file, but to restore the file I have to manually go to the trash and restore. I should not need to go away from the app to do that.

Won't happen. IIRC wrangling the trash programmatically is a can of worms, and (apart from the non confirmation bug) no other OS X application works that way.

**Comment by pvinis** [comment]
I know. and that's why it should ask before moving to trash. maker it harder to move to trash accidentally.
